Repository moff-station/moff-station-14, pull requests merged in 2025-05, with the labels that each got.

#143 Added Sawa Tar's uniform to the loadout list
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#142 Added Pawgliaci
  Resources/Locale/en-US/_Moffstation/interaction/interaction-popup-component.ftl
  Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/NPCs/pawgliaci.yml
  Resources/Textures/_Moffstation/Mobs/Pets/pawgliaci.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Pets/pawgliaci.rsi/pawgliaci-crit.png
  Resources/Textures/_Moffstation/Mobs/Pets/pawgliaci.rsi/pawgliaci-dead.png
  Resources/Textures/_Moffstation/Mobs/Pets/pawgliaci.rsi/pawgliaci.png
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#144 Strawberry's Tentacles Personal item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Vivensshadow/Strawberry_Petal/backtentacles.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Compilatron/Tania_Buttersworth/backtentacles.rsi/equipped-BACKPACK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Vivensshadow/Strawberry_Petal/backtentacles.rsi/equipped-BACKPACK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Vivensshadow/Strawberry_Petal/backtentacles.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Vivensshadow/Strawberry_Petal/backtentacles.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#92 Engi Gear Buffs
  Resources/Prototypes/Entities/Clothing/Head/hardhats.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/vests.yml
Labels: Changes: No C#, S: Untriaged

#145 Change Strawberry's personal item to updated in-game name
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Vivensshadow/Strawberry_Petal/backtentacles.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#153 Fixed arrivals and evac not docking properly
  Content.Server/Shuttles/Systems/DockingSystem.Shuttle.cs
Labels: size/S, S: Untriaged

#154 Bulk maid dress crate
  Resources/Prototypes/_Moffstation/Catalog/Cargo/cargo_fun.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Crates/fun.yml
Labels: Changes: No C#

#147 Admeme Shuttles - NT
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/_Moffstation/Shuttles/shuttle-nt-bureaucrat.yml
  Resources/Maps/_Moffstation/Shuttles/shuttle-nt-businessclass.yml
  Resources/Maps/_Moffstation/Shuttles/shuttle-nt-equilibrium.yml
  Resources/Maps/_Moffstation/Shuttles/shuttle-nt-grimebreaker.yml
  Resources/Maps/_Moffstation/Shuttles/shuttle-nt-lockup.yml
  Resources/Maps/_Moffstation/Shuttles/shuttle-nt-situationroom.yml
  Resources/Maps/_Moffstation/Shuttles/shuttle-nt-vacator.yml
  Resources/Maps/_Moffstation/Shuttles/shuttle-tbe-artificer.yml
Labels: Changes: No C#, S: Untriaged, Changes: Map, size/XL

#146 Personal Items: Jasmine's flower and Remia's photo
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/freianofvoid/Remia/remiaphoto.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/freianofvoid/Jasmine_Whitewitch/jasmineflower.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/freianofvoid/Remia/remiaphoto.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/freianofvoid/Remia/remiaphoto.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Jasmine_Whitewitch/jasminflower.rsi/equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Jasmine_Whitewitch/jasminflower.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Jasmine_Whitewitch/jasminflower.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#148 Captain's Persona Saber
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Fun/pai.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
  Resources/Prototypes/tags.yml
Labels: S: Needs Review, Changes: No C#, size/S

#155 Spray Painter Overhaul
  Resources/Prototypes/Entities/Objects/Tools/spray_painter.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#156 Corgi Meat Vestine
  Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml
Labels: Changes: No C#, size/XS, S: Untriaged, Changes: Sprites

#151 Reporter Item: Shift-report notebook
  Content.Server/GameTicking/GameTicker.RoundFlow.cs
  Content.Server/_Moffstation/RoundReport/RoundReportSystem.cs
  Content.Shared/Paper/PaperComponent.cs
  Content.Shared/Paper/PaperSystem.cs
  Content.Shared/_Moffstation/RoundReport/Components/RoundReportComponent.cs
  Content.Shared/_Moffstation/RoundReport/Systems/ReporterShiftReportSystem.cs
  Resources/Locale/en-US/_Moffstation/round-end/round-end-text.ftl
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/reporter-shift-report.yml
  Resources/Textures/_Moffstation/Interface/Paper/paper_background_tablet.svg.96dpi.png
  Resources/Textures/_Moffstation/Interface/Paper/paper_background_tablet.svg.96dpi.png.yml
  Resources/Textures/_Moffstation/Interface/Paper/paper_content_tablet.svg.96dpi.png
  Resources/Textures/_Moffstation/Interface/Paper/paper_content_tablet.svg.96dpi.png.yml
  Resources/Textures/_Moffstation/Objects/Fun/shiftreporttablet.rsi/equipped-BELT.png
  Resources/Textures/_Moffstation/Objects/Fun/shiftreporttablet.rsi/icon.png
  Resources/Textures/_Moffstation/Objects/Fun/shiftreporttablet.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Objects/Fun/shiftreporttablet.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Objects/Fun/shiftreporttablet.rsi/meta.json
Labels: size/M, Changes: Sprites

#157 Fixes Remia's name
  Resources/Prototypes/_Moffstation/PersonalItems/Items/freianofvoid/Remia/remiaphoto.yml
Labels: Changes: No C#, S: Untriaged

#160 Added the Foolbox
  Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Lockers/clown.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/foolbox.yml
  Resources/Prototypes/_Moffstation/Entities/Structures/Storage/Closets/Lockers/clown.yml
  Resources/Textures/_Moffstation/Objects/Fun/foolbox.rsi/icon-open.png
  Resources/Textures/_Moffstation/Objects/Fun/foolbox.rsi/icon.png
  Resources/Textures/_Moffstation/Objects/Fun/foolbox.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Objects/Fun/foolbox.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Objects/Fun/foolbox.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#162 Adds missing Harmony criminal HUD icons
  Content.Shared/CriminalRecords/Systems/SharedCriminalRecordsSystem.cs
  Resources/Prototypes/_Harmony/StatusIcon/security.yml
  Resources/Textures/_Harmony/Interface/Misc/security_icons.rsi/hud_monitor.png
  Resources/Textures/_Harmony/Interface/Misc/security_icons.rsi/hud_search.png
  Resources/Textures/_Harmony/Interface/Misc/security_icons.rsi/meta.json
Labels: size/S, Changes: Sprites

#158 Readded Hardsuits to traitor uplink
  Resources/Prototypes/Catalog/uplink_catalog.yml
Labels: Changes: No C#

#43 Personal Item: Arie Barry's golden apple plush
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Artycookie/Arie_Barry/arieapple.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/Artycookie/Arie_Barry/arieapple.rsi/arieapple-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Artycookie/Arie_Barry/arieapple.rsi/arieapple-inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Artycookie/Arie_Barry/arieapple.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Artycookie/Arie_Barry/arieapple.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#161 Hopefully the final evacpod fix
  Content.IntegrationTests/Tests/SaveLoadSaveTest.cs
  Content.Server/Shuttles/Systems/DockingSystem.cs
  Content.Shared/Doors/DoorEvents.cs
  Content.Shared/Doors/Systems/SharedAirlockSystem.cs
  Content.Shared/Doors/Systems/SharedDoorSystem.cs
Labels: S: Untriaged, size/M

#163 Open-Ended objectives
  Content.Server/_Moffstation/Objectives/Components/DisruptionObjectiveComponent.cs
  Content.Server/_Moffstation/Objectives/Components/GreytextObjectiveComponent.cs
  Content.Server/_Moffstation/Objectives/Components/PickRandomDepartmentComponent.cs
  Content.Server/_Moffstation/Objectives/Components/PickSpecificDepartmentComponent.cs
  Content.Server/_Moffstation/Objectives/Components/SimpleObjectiveComponent.cs
  Content.Server/_Moffstation/Objectives/Components/TargetDepartmentComponent.cs
  Content.Server/_Moffstation/Objectives/Components/TargetDepartmentOverrideComponent.cs
  Content.Server/_Moffstation/Objectives/Systems/DisruptionObjectiveSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/GreytextObjectiveSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/PickObjectiveDepartmentSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/SimpleObjectiveSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/TargetDepartmentSystem.cs
  Resources/Locale/en-US/_Moffstation/objectives/conditions/open-objective.ftl
  Resources/Locale/en-US/job/department.ftl
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/_Moffstation/Objectives/open_objectives.yml
Labels: S: Untriaged, size/M

#164 Vortex personal mask
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/catlord09-/Vortex_Vatia/floralmask.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/catlord09-/Vortex_Vatia/floralmask.rsi/equipped-MASK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/catlord09-/Vortex_Vatia/floralmask.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/catlord09-/Vortex_Vatia/floralmask.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/catlord09-/Vortex_Vatia/floralmask.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/catlord09-/Vortex_Vatia/floralmask.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#150 Added staminia resistance to armor and hardsuits
  Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/vests.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Objects/Weapons/security.yml
  Resources/Prototypes/Research/arsenal.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M

#168 Increase moff speech sfx
  Resources/Audio/_Moffstation/Voice/Talk/moth.ogg
  Resources/Audio/_Moffstation/Voice/Talk/moth_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/moth_exclaim.ogg
Labels: size/XS, S: Untriaged

#170 Evac pods shower thoughts
  Content.Server/Shuttles/Systems/DockingSystem.Shuttle.cs
Labels: size/S, S: Untriaged

#171 Caustic damage can now acidify
  Resources/Prototypes/Entities/Mobs/base.yml
  Resources/Prototypes/Reagents/toxins.yml
Labels: Changes: No C#, size/S

#172 Biogens are Lube compatible
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: Changes: No C#, S: Untriaged

#165 Persona Saber Fixes
  Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
Labels: Changes: No C#

#149 Survival Boxes but Cool
  Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml
  Resources/Prototypes/Catalog/Fills/Boxes/general.yml
  Resources/Prototypes/Entities/Clothing/Masks/base_clothingmask.yml
  Resources/Prototypes/Entities/Clothing/Masks/masks.yml
  Resources/Prototypes/Entities/Clothing/Masks/specific.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
  Resources/Prototypes/Entities/Objects/Tools/flare.yml
  Resources/Prototypes/Entities/Objects/Tools/gas_tanks.yml
  Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
  Resources/Prototypes/tags.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M

#177 Revert "Hack to make record consoles work again (#119)"
  Content.Server/_CD/Records/Consoles/CharacterRecordConsoleSystem.cs
Labels: size/S, S: Untriaged

#176 Fixed water bottles not fitting in boxes
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
  Resources/Prototypes/_Moffstation/tags.yml
  Resources/Prototypes/tags.yml
Labels: Changes: No C#, size/S, S: Untriaged

#180 Reimplement "Hack to make record consoles work again (#119)""
  Content.Server/_CD/Records/Consoles/CharacterRecordConsoleSystem.cs
Labels: size/S, S: Untriaged

#178 Tabletop computers
  Resources/Prototypes/_CD/Entities/Structures/Machines/Computers/tabletopcomputer.yml
  Resources/Textures/_CD/Structures/Machines/Computers/tabletopcomputer.rsi/broken_tabletop.png
  Resources/Textures/_CD/Structures/Machines/Computers/tabletopcomputer.rsi/computer_tabletop.png
  Resources/Textures/_CD/Structures/Machines/Computers/tabletopcomputer.rsi/generic_keyboard_tabletop.png
  Resources/Textures/_CD/Structures/Machines/Computers/tabletopcomputer.rsi/meta.json
Labels: Changes: No C#, size/M, Changes: Sprites

#179 Cool arrivals
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Content.Server/Shuttles/Systems/ArrivalsSystem.cs
  Content.Server/_CD/Spawners/ArrivalsSpawnPointComponent.cs
  Content.Server/_CD/Spawners/ArrivalsSpawnPointSystem.cs
  Content.Shared/CCVar/CCVars.Shuttle.cs
  Content.Shared/Roles/JobPrototype.cs
  Resources/Maps/_Umbra/Misc/terminal.yml
  Resources/Prototypes/Roles/Jobs/Science/borg.yml
  Resources/Prototypes/_CD/Entities/Markers/Spawners/jobs.yml
Labels: S: Needs Review, S: Untriaged, Changes: Sprites, Changes: Map, size/XL

#186 Dragons no longer round remove cyborgs when devouring them
  Content.Server/Devour/DevourSystem.cs
Labels: size/S, S: Untriaged

#182 Prisoner role
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Content.Server/GameTicking/GameTicker.Spawning.cs
  Content.Server/_CD/Spawners/ArrivalsSpawnPointSystem.cs
  Content.Shared/Roles/JobPrototype.cs
  Resources/Locale/en-US/_CD/job/job-description.ftl
  Resources/Maps/_Umbra/Misc/terminal.yml
  Resources/Prototypes/Maps/amber.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/core.yml
  Resources/Prototypes/Maps/elkridge.yml
  Resources/Prototypes/Maps/loop.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/packed.yml
  Resources/Prototypes/Maps/plasma.yml
  Resources/Prototypes/Maps/train.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/_CD/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/_CD/Entities/Objects/Devices/Misc/identification_cards.yml
  Resources/Prototypes/_CD/Roles/Jobs/Wildcards/prisoner.yml
  Resources/Prototypes/_CD/Roles/play_time_trackers.yml
Labels: S: Untriaged, size/M, Changes: Sprites, Changes: Map

#184 Departmental Maid Dresses
  Resources/Prototypes/Catalog/VendingMachines/Inventories/atmosdrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/bardrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/cargodrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chemdrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/scidrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
  Resources/Prototypes/_Moffstation/Catalog/Cargo/cargo_fun.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_atmos.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_atmos.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_atmos.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_atmos.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_atmos.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_atmos.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_cargo.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_cargo.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_cargo.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_cargo.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_cargo.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_cargo.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_chem.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_chem.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_chem.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_chem.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_chem.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_chem.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_science.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_science.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_science.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_science.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_science.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_science.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_sec.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_sec.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_sec.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_sec.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_sec.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_sec.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_service.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_service.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_service.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_service.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_service.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/maid_service.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/M, Changes: Sprites

#188 Revert "lower playercount requirements for nukies and zombies"
  Resources/Prototypes/GameRules/roundstart.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#181 Wireless handheld camera
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Research/civilianservices.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Tools/handheld_camera.yml
  Resources/Textures/_Moffstation/Objects/Tools/handheld_camera.rsi/icon.png
  Resources/Textures/_Moffstation/Objects/Tools/handheld_camera.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Objects/Tools/handheld_camera.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Objects/Tools/handheld_camera.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, Changes: Sprites

#185 Nurse Outfit
  Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/_Moffstation/Loadouts/Non-Antags/clothing-medical.yml
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/nursesuit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/nursesuit.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/nursesuit.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/nursesuit.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/nursesuit.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#189 Cherry-pick Map renderer rework (#37306)
  Content.MapRenderer/CommandLineArguments.cs
  Content.MapRenderer/Painters/DecalPainter.cs
  Content.MapRenderer/Painters/EntityPainter.cs
  Content.MapRenderer/Painters/GridPainter.cs
  Content.MapRenderer/Painters/MapPainter.cs
  Content.MapRenderer/Painters/TilePainter.cs
  Content.MapRenderer/Program.cs
Labels: S: Untriaged, size/M

#194 Reporter Content
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Lockers/reporter.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/reporter-shift-report.yml
  Resources/Prototypes/_Moffstation/Entities/Structures/Storage/Closets/Lockers/reporter.yml
  Resources/Prototypes/_Moffstation/Loadouts/Non-Antags/clothing-service.yml
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/journalist.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/journalist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/journalist.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/journalist.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/journalist.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/journalist.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/reporter.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/reporter.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/reporter.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/reporter.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/reporter.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/reporter.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/meta.json
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/locked.png
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/meta.json
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/reporter.png
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/reporter_door.png
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/reporter_open.png
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/secure.png
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/secure_door.png
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/secure_open.png
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/sparking.png
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/unlocked.png
  Resources/Textures/_Moffstation/Structures/Storage/closet.rsi/welded.png
Labels: Changes: No C#, size/M, Changes: Sprites

#195 Arrivals - Added Reporter
  Resources/Maps/_Umbra/Misc/terminal.yml
  Resources/Prototypes/_CD/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/_Moffstation/Entities/Markers/Spawners/jobs.yml
Labels: Changes: No C#, Changes: Map, size/L

#191 fire safety (Hot Sauce's personal item)
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/HotrodMcCoolgal/Hot_Sauce/hotsaucefireextinguisher.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/HotrodMcCoolgal/Hot_Sauce/hotsaucefireextinguisher.rsi/fire_extinguisher_closed.png
  Resources/Textures/_Moffstation/PersonalItems/Items/HotrodMcCoolgal/Hot_Sauce/hotsaucefireextinguisher.rsi/fire_extinguisher_open.png
  Resources/Textures/_Moffstation/PersonalItems/Items/HotrodMcCoolgal/Hot_Sauce/hotsaucefireextinguisher.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/HotrodMcCoolgal/Hot_Sauce/hotsaucefireextinguisher.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/HotrodMcCoolgal/Hot_Sauce/hotsaucefireextinguisher.rsi/meta.json
Labels: Changes: No C#, size/S, Changes: Sprites

#193 Launcher Tweaks
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
Labels: S: Needs Review, Changes: No C#, size/S

#200 Removed Incriminate Objective - Added Calling Card Objectives
  Resources/Locale/en-US/_Moffstation/objectives/conditions/open-objective.ftl
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Prototypes/_Moffstation/Objectives/open_objectives.yml
Labels: Changes: No C#, size/S, S: Untriaged

#202 Peri mask
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/zangothedino/Periwinkle_Candyfloss/periwinklemask.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/zangothedino/Periwinkle_Candyfloss/periwinklemask.rsi/equipped-MASK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/zangothedino/Periwinkle_Candyfloss/periwinklemask.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/zangothedino/Periwinkle_Candyfloss/periwinklemask.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/zangothedino/Periwinkle_Candyfloss/periwinklemask.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/zangothedino/Periwinkle_Candyfloss/periwinklemask.rsi/meta.json
Labels: Changes: No C#, size/S, Changes: Sprites

#203 Modified Terminal and Arrivals Shuttle
  Resources/Maps/_Moffstation/Shuttles/arrivals.yml
  Resources/Maps/_Umbra/Misc/terminal.yml
  Resources/Prototypes/Entities/Stations/base.yml
Labels: Changes: No C#, Changes: Map, size/L

#207 Fixed Frost's personal item not spawning
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/FrostWinters/Frost_Winters/frostmedicalwebbing.yml
Labels: Changes: No C#, size/XS

#206 Bulldog Buff
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
Labels: Changes: No C#, size/XS

#210 Added new Moffstation logo
  Content.Client/MainMenu/UI/MainMenuControl.xaml.cs
  Content.Replay/Menu/ReplayMainMenuControl.xaml.cs
  README.md
  Resources/Textures/_Moffstation/Logo/attributions.yml
  Resources/Textures/_Moffstation/Logo/icon.ico
  Resources/Textures/_Moffstation/Logo/icon/icon-128x128.png
  Resources/Textures/_Moffstation/Logo/icon/icon-16x16.png
  Resources/Textures/_Moffstation/Logo/icon/icon-24x24.png
  Resources/Textures/_Moffstation/Logo/icon/icon-256x256.png
  Resources/Textures/_Moffstation/Logo/icon/icon-32x32.png
  Resources/Textures/_Moffstation/Logo/icon/icon-48x48.png
  Resources/Textures/_Moffstation/Logo/icon/icon-64x64.png
  Resources/Textures/_Moffstation/Logo/logo.png
  Resources/Textures/_Moffstation/Logo/logo.png.yml
  Resources/Textures/_Moffstation/Logo/logo.svg
  Resources/manifest.yml
Labels: size/S, S: Untriaged, Changes: UI

#208 IFF tag (Aurora Epiolos's personal item)
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPin.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPin.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPin.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPin.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPinInversed.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPinInversed.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPinInversed.rsi/meta.json
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#216 Hotfix: Aurora's personal item
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPin.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#212 Added Rules
  Resources/Locale/en-US/_Moffstation/guidebook/guides.ftl
  Resources/Prototypes/_Moffstation/Guidebook/rules.yml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffMetashield.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffMetashieldChanges.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR1OOC.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR2Metagaming.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR3Powergaming.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR4RP.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR5DeathAndLife.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR6EOR.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR7Crew.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR8Antags.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR9Prisoners.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffRules.xml
Labels: Changes: No C#, size/M

#215 Early access Meta station
  Resources/Maps/meta.yml
  Resources/Prototypes/Maps/meta.yml
Labels: Changes: No C#, S: Untriaged, Changes: Map, size/XL

#217 Dino Nuggies
  Resources/Prototypes/_Moffstation/Recipes/Cooking/meal_recipes.yml
Labels: Changes: No C#, size/S, S: Untriaged

#218 Arrivals Shuttle - Fixed Wiring Issues
  Resources/Maps/_Moffstation/Shuttles/arrivals.yml
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Map

#220 Prisoner Improvements
  Resources/Locale/en-US/_Umbra/preferences/loadouts.ftl
  Resources/Prototypes/_CD/Roles/Jobs/Wildcards/prisoner.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Head/prisoner.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Devices/Misc/identification_cards.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/_Moffstation/Loadouts/Non-Antags/prisoner.yml
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/Loadouts/role_loadouts.yml
  Resources/Textures/Objects/Devices/pda.rsi/meta.json
  Resources/Textures/Objects/Devices/pda.rsi/pda-prisoner.png
  Resources/Textures/_Moffstation/Clothing/Head/Hats/striped-hat.rsi/equipped-HELMET-hamster.png
  Resources/Textures/_Moffstation/Clothing/Head/Hats/striped-hat.rsi/equipped-HELMET.png
  Resources/Textures/_Moffstation/Clothing/Head/Hats/striped-hat.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Head/Hats/striped-hat.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Head/Hats/striped-hat.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Head/Hats/striped-hat.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisonerstriped.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisonerstriped.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisonerstriped.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisonerstriped.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisonerstriped.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisonerstriped.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisonerstriped.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisonerstriped.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisonerstriped.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisonerstriped.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisonerstriped.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisonerstriped.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/meta.json
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#219 Lobby pausing
  Content.Server/GameTicking/GameTicker.Player.cs
  Content.Server/GameTicking/GameTicker.cs
  Content.Server/Voting/Managers/VoteManager.DefaultVotes.cs
  Content.Shared/CCVar/CCVars.Server.cs
  Content.Shared/CCVar/CCVars.Vote.cs
  Resources/Locale/en-US/_Moffstation/voting/voting.ftl
Labels: size/S, S: Untriaged

#221 Map voting improvements
  Content.Server/Maps/GameMapManager.cs
  Content.Server/Maps/IGameMapManager.cs
  Content.Server/RoundEnd/RoundEndSystem.cs
  Content.Server/Voting/Managers/VoteManager.DefaultVotes.cs
  Content.Shared/CCVar/CCVars.Vote.cs
Labels: S: Needs Review, S: Untriaged, size/M

#222 Fixes Vivonic's personal item
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Vivensshadow/Vivonic_Rose/vivmantle.yml
Labels: Changes: No C#, S: Untriaged

#225 Sapphire item fix
  Resources/Textures/_Moffstation/PersonalItems/Wearables/SapphireMaris/Sapphire_Maris/sapphireampule.rsi/icon.png
Labels: Changes: No C#, size/XS, S: Untriaged, Changes: Sprites

#224 CMO Scarf
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Neck/scarfs.yml
  Resources/Prototypes/_Moffstation/Loadouts/Non-Antags/clothing-medical.yml
  Resources/Textures/_Moffstation/Clothing/Neck/Scarfs/cmoscarf.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/Clothing/Neck/Scarfs/cmoscarf.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Neck/Scarfs/cmoscarf.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Neck/Scarfs/cmoscarf.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Neck/Scarfs/cmoscarf.rsi/meta.json
Labels: Changes: No C#, Changes: Sprites

#226 Colorful headphones
  Resources/Prototypes/Entities/Clothing/Neck/misc.yml
  Resources/Textures/_Moffstation/Clothing/Neck/Misc/headphones.rsi/icon-on.png
  Resources/Textures/_Moffstation/Clothing/Neck/Misc/headphones.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Neck/Misc/headphones.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Neck/Misc/headphones.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Neck/Misc/headphones.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Neck/Misc/headphones.rsi/off-equipped-NECK.png
  Resources/Textures/_Moffstation/Clothing/Neck/Misc/headphones.rsi/on-equipped-NECK.png
Labels: Changes: No C#, S: Untriaged, Changes: Sprites

#223 New lobby backgrounds
  Resources/Prototypes/_Moffstation/lobbyscreens.yml
  Resources/Textures/_Moffstation/LobbyScreens/attributions.yml
  Resources/Textures/_Moffstation/LobbyScreens/sapphire-hunting-arie.png
  Resources/Textures/_Moffstation/LobbyScreens/sapphire-hunting-arie.png.yml
  Resources/Textures/_Moffstation/LobbyScreens/t-minus.png
  Resources/Textures/_Moffstation/LobbyScreens/t-minus.png.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#227 Contribution guideline changes
  CONTRIBUTING.md
Labels: Changes: No C#, size/XS

#228 Map winner fix
  Content.Server/Voting/Managers/VoteManager.DefaultVotes.cs
Labels: size/XS, S: Untriaged

#230 Add a safety net for round controls in the admin window.
  Content.Client/Administration/UI/Tabs/RoundTab.xaml
  Content.Client/Administration/UI/Tabs/RoundTab.xaml.cs
Labels: size/S, S: Untriaged, Changes: UI

#201 Hugbot
  Content.Client/Silicons/Bots/HugBotSystem.cs
  Content.Server/NPC/HTN/Preconditions/IsEmaggedPrecondition.cs
  Content.Server/NPC/HTN/PrimitiveTasks/Operators/Combat/Melee/MeleeAttackOperator.cs
  Content.Server/NPC/HTN/PrimitiveTasks/Operators/SpeakOperator.cs
  Content.Server/NPC/HTN/PrimitiveTasks/Operators/Specific/RaiseEventForOwnerOperator.cs
  Content.Server/NPC/Queries/Queries/ComponentFilter.cs
  Content.Server/NPC/Systems/NPCUtilitySystem.cs
  Content.Server/Silicons/Bots/HugBotSystem.cs
  Content.Server/Silicons/Bots/RecentlyHuggedByHugBotComponent.cs
  Content.Shared/Silicons/Bots/HugBotComponent.cs
  Content.Shared/Silicons/Bots/SharedHugBotSystem.cs
  Resources/Locale/en-US/_Moffstation/recipes/tags.ftl
  Resources/Locale/en-US/npc/hugbot.ftl
  Resources/Prototypes/Body/Prototypes/bot.yml
  Resources/Prototypes/Catalog/hugbot.yml
  Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
  Resources/Prototypes/NPCs/debug.yml
  Resources/Prototypes/NPCs/firebot.yml
  Resources/Prototypes/NPCs/hugbot.yml
  Resources/Prototypes/NPCs/medibot.yml
  Resources/Prototypes/Recipes/Crafting/Graphs/bots/hugbot.yml
  Resources/Prototypes/Recipes/Crafting/bots.yml
  Resources/Textures/Mobs/Silicon/Bots/hugbot.rsi/hugbot.png
  Resources/Textures/Mobs/Silicon/Bots/hugbot.rsi/meta.json
Labels: S: Untriaged, size/M, Changes: Sprites

#235 HOTFIX: give Avali their starting supply kits
  Resources/Prototypes/Loadouts/Miscellaneous/survival.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#237 Fix changelog
  Tools/actions_changelogs_since_last_run.py
Labels: Changes: No C#, size/XS

#238 Revert "Fix changelog"
  Tools/actions_changelogs_since_last_run.py
Labels: Changes: No C#, size/XS

#233 Law Matrix Imprinter
  Resources/Locale/en-US/_Moffstation/research/technologies.ftl
  Resources/Prototypes/Recipes/Lathes/Packs/science.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/_Moffstation/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/_Moffstation/Recipes/Lathes/Packs/Science.yml
  Resources/Prototypes/_Moffstation/Recipes/Lathes/base_electronics.yml
  Resources/Prototypes/_Moffstation/Recipes/Lathes/machine_boards.yml
  Resources/Prototypes/_Moffstation/Research/experimental.yml
  Resources/Textures/_Moffstation/Structures/Machines/circuit_imprinter_law_matrix.rsi/building.png
  Resources/Textures/_Moffstation/Structures/Machines/circuit_imprinter_law_matrix.rsi/icon.png
  Resources/Textures/_Moffstation/Structures/Machines/circuit_imprinter_law_matrix.rsi/meta.json
  Resources/Textures/_Moffstation/Structures/Machines/circuit_imprinter_law_matrix.rsi/panel.png
  Resources/Textures/_Moffstation/Structures/Machines/circuit_imprinter_law_matrix.rsi/unlit.png
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#242 Hotsauce personal item definition fix
  Resources/Prototypes/_Moffstation/PersonalItems/Items/HotrodMcCoolgal/Hot_Sauce/hotsaucefireextinguisher.yml
Labels: Changes: No C#, S: Untriaged

#211 added ability to pick cat ears and cat tail as human
  Resources/Prototypes/Species/human.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#214 (s)tar fruit
  Resources/Locale/en-US/_Moffstation/flavors/flavor-profiles.ftl
  Resources/Locale/en-US/_Moffstation/ghost/ghost-role-component.ftl
  Resources/Locale/en-US/_Moffstation/nutrition/components/food-sequence.ftl
  Resources/Locale/en-US/_Moffstation/reagents/meta/consumable/drink/juice.ftl
  Resources/Locale/en-US/_Moffstation/seeds/seeds.ftl
  Resources/Prototypes/Catalog/VendingMachines/Inventories/seeds.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/NPCs/tarbold.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Consumable/Food/burger.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/Hydroponics/seeds.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/Rehydrateable.yml
  Resources/Prototypes/_Moffstation/Flavors/flavors.yml
  Resources/Prototypes/_Moffstation/Hydroponics/seeds.yml
  Resources/Prototypes/_Moffstation/Reagents/Consumable/Drink/Juice.yml
  Resources/Prototypes/_Moffstation/Recipes/Cooking/food_sequence_element.yml
  Resources/Prototypes/_Moffstation/Recipes/Cooking/meal_recipes.yml
  Resources/Prototypes/_Moffstation/name_identifier_groups.yml
  Resources/Prototypes/name_identifier_groups.yml
  Resources/Textures/_Moffstation/Mobs/Animals/tarbold.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Animals/tarbold.rsi/outline.png
  Resources/Textures/_Moffstation/Mobs/Animals/tarbold.rsi/tarbold.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/tarburger.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/dead.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/harvest.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/produce-inhand-left.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/produce-inhand-right.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/produce.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/seed.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-1.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-2.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-3.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-4.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-5.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-6.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/dead.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/harvest.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/produce-inhand-left.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/produce-inhand-right.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/produce-unwrapped.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/produce.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/seed.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-1.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-2.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-3.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-4.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-5.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-6.png
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#249 Revert "Squeakify moff sfx (#101)"
  Resources/Audio/_Moffstation/Voice/Talk/attributions.yml
  Resources/Audio/_Moffstation/Voice/Talk/moth.ogg
  Resources/Audio/_Moffstation/Voice/Talk/moth_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/moth_exclaim.ogg
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/Species/moth.yml
  Resources/Prototypes/_Moffstation/Voice/speech_sounds.yml
Labels: size/S, S: Untriaged

#251 Revert upstream merged "Decouple Lights from Toggleable Visuals"
  Content.Client/Light/HandheldLightSystem.cs
  Content.Client/Toggleable/ToggleableLightVisualsSystem.cs
  Content.Server/Atmos/EntitySystems/FlammableSystem.cs
  Content.Shared/Light/Components/ItemTogglePointLightComponent.cs
  Content.Shared/Light/EntitySystems/ItemTogglePointLightSystem.cs
  Content.Shared/Light/SharedHandheldLightSystem.cs
  Content.Shared/Toggleable/ToggleActionEvent.cs
  Content.Shared/Toggleable/ToggleableLightVisuals.cs
  Content.Shared/Weapons/Melee/EnergySword/EnergySwordSystem.cs
  Content.Shared/Weapons/Misc/SharedTetherGunSystem.cs
  Resources/Prototypes/Entities/Clothing/Head/base_clothinghead.yml
  Resources/Prototypes/Entities/Clothing/Head/hardhats.yml
  Resources/Prototypes/Entities/Objects/Misc/fluff_lights.yml
  Resources/Prototypes/Entities/Objects/Tools/decoys.yml
  Resources/Prototypes/Entities/Objects/Tools/flashlights.yml
  Resources/Prototypes/Entities/Objects/Tools/lantern.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
Labels: size/S, S: Untriaged

#248 Make more objects spray paintable
  Content.Client/Atmos/EntitySystems/GasCanisterAppearanceSystem.cs
  Content.Client/Doors/DoorSystem.cs
  Content.Client/SprayPainter/SprayPainterSystem.cs
  Content.Client/SprayPainter/UI/SprayPainterBoundUserInterface.cs
  Content.Client/SprayPainter/UI/SprayPainterDecals.xaml
  Content.Client/SprayPainter/UI/SprayPainterDecals.xaml.cs
  Content.Client/SprayPainter/UI/SprayPainterGroup.xaml
  Content.Client/SprayPainter/UI/SprayPainterGroup.xaml.cs
  Content.Client/SprayPainter/UI/SprayPainterWindow.xaml
  Content.Client/SprayPainter/UI/SprayPainterWindow.xaml.cs
  Content.Client/Storage/Visualizers/EntityStorageVisualizerSystem.cs
  Content.Server/SprayPainter/SprayPainterSystem.cs
  Content.Shared/Doors/Components/DoorComponent.cs
  Content.Shared/SprayPainter/Components/PaintableAirlockComponent.cs
  Content.Shared/SprayPainter/Components/PaintableComponent.cs
  Content.Shared/SprayPainter/Components/PaintedComponent.cs
  Content.Shared/SprayPainter/Components/SprayPainterAmmo.cs
  Content.Shared/SprayPainter/Components/SprayPainterComponent.cs
  Content.Shared/SprayPainter/Prototypes/PaintableGroupCategoryPrototype.cs
  Content.Shared/SprayPainter/Prototypes/PaintableGroupPrototype.cs
  Content.Shared/SprayPainter/SharedSprayPainterSystem.cs
  Content.Shared/SprayPainter/SprayPainterAmmoSystem.cs
  Content.Shared/SprayPainter/SprayPainterEvents.cs
  Resources/Locale/en-US/engineer-painter/engineer-painter.ftl
  Resources/Locale/en-US/spray-painter/spray-painter.ftl
  Resources/Prototypes/Catalog/VendingMachines/Inventories/youtool.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Entities/Objects/Tools/spray_painter.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/airlocks.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/clockwork.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/external.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/shuttle.yml
  Resources/Prototypes/Entities/Structures/Doors/airlock_groups.yml
  Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/base_structurelockers.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/base_structureclosets.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/wall_lockers.yml
  Resources/Prototypes/Entities/Structures/Storage/Crates/base_structurecrates.yml
  Resources/Prototypes/Entities/Structures/Storage/Crates/crates.yml
  Resources/Prototypes/Paintables/airlock_groups.yml
  Resources/Prototypes/Paintables/canister_groups.yml
  Resources/Prototypes/Paintables/categories.yml
  Resources/Prototypes/Paintables/crate_groups.yml
  Resources/Prototypes/Paintables/locker_groups.yml
  Resources/Prototypes/Recipes/Lathes/Packs/engineering.yml
  Resources/Prototypes/Recipes/Lathes/tools.yml
  Resources/Textures/Objects/Tools/spray_painter.rsi/ammo-inhand-left.png
  Resources/Textures/Objects/Tools/spray_painter.rsi/ammo-inhand-right.png
  Resources/Textures/Objects/Tools/spray_painter.rsi/ammo.png
  Resources/Textures/Objects/Tools/spray_painter.rsi/meta.json
Labels: Changes: Sprites, Changes: UI, size/L

#252 Early Merge - Waterjug Station
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Locale/en-US/stack/stacks.ftl
  Resources/Locale/en-US/tiles/tiles.ftl
  Resources/Maps/Shuttles/emergency_adriatic.yml
  Resources/Maps/Waterjug.yml
  Resources/Prototypes/Entities/Objects/Misc/tiles.yml
  Resources/Prototypes/Maps/waterjug.yml
  Resources/Prototypes/Recipes/Lathes/Packs/science.yml
  Resources/Prototypes/Recipes/Lathes/misc.yml
  Resources/Prototypes/Research/civilianservices.yml
  Resources/Prototypes/Stacks/floor_tile_stacks.yml
  Resources/Prototypes/Tiles/floors.yml
  Resources/Textures/Objects/Tiles/tile.rsi/desertsand-inhand-left.png
  Resources/Textures/Objects/Tiles/tile.rsi/desertsand-inhand-right.png
  Resources/Textures/Objects/Tiles/tile.rsi/desertsand.png
  Resources/Textures/Objects/Tiles/tile.rsi/grassdark-inhand-left.png
  Resources/Textures/Objects/Tiles/tile.rsi/grassdark-inhand-right.png
  Resources/Textures/Objects/Tiles/tile.rsi/grassdark.png
  Resources/Textures/Objects/Tiles/tile.rsi/grasslight-inhand-left.png
  Resources/Textures/Objects/Tiles/tile.rsi/grasslight-inhand-right.png
  Resources/Textures/Objects/Tiles/tile.rsi/grasslight.png
  Resources/Textures/Objects/Tiles/tile.rsi/meta.json
Labels: S: Needs Review, Changes: Sprites, Changes: Map, size/XL

#253 Revert "(s)tar fruit"
  Resources/Locale/en-US/_Moffstation/flavors/flavor-profiles.ftl
  Resources/Locale/en-US/_Moffstation/ghost/ghost-role-component.ftl
  Resources/Locale/en-US/_Moffstation/nutrition/components/food-sequence.ftl
  Resources/Locale/en-US/_Moffstation/reagents/meta/consumable/drink/juice.ftl
  Resources/Locale/en-US/_Moffstation/seeds/seeds.ftl
  Resources/Prototypes/Catalog/VendingMachines/Inventories/seeds.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/NPCs/tarbold.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Consumable/Food/burger.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/Hydroponics/seeds.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/Rehydrateable.yml
  Resources/Prototypes/_Moffstation/Flavors/flavors.yml
  Resources/Prototypes/_Moffstation/Hydroponics/seeds.yml
  Resources/Prototypes/_Moffstation/Reagents/Consumable/Drink/Juice.yml
  Resources/Prototypes/_Moffstation/Recipes/Cooking/food_sequence_element.yml
  Resources/Prototypes/_Moffstation/Recipes/Cooking/meal_recipes.yml
  Resources/Prototypes/_Moffstation/name_identifier_groups.yml
  Resources/Prototypes/name_identifier_groups.yml
  Resources/Textures/_Moffstation/Mobs/Animals/tarbold.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Animals/tarbold.rsi/outline.png
  Resources/Textures/_Moffstation/Mobs/Animals/tarbold.rsi/tarbold.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/tarburger.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/dead.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/harvest.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/produce-inhand-left.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/produce-inhand-right.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/produce.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/seed.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-1.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-2.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-3.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-4.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-5.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/starfruit.rsi/stage-6.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/dead.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/harvest.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/produce-inhand-left.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/produce-inhand-right.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/produce-unwrapped.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/produce.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/seed.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-1.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-2.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-3.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-4.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-5.png
  Resources/Textures/_Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi/stage-6.png
Labels: Changes: No C#, Changes: Sprites
