Repository moff-station/moff-station-14, pull requests merged in 2025-10, with the labels that each got.

#609 Added cvar for longspeech
  Content.Server/Speech/SpeechNoiseSystem.cs
  Content.Shared/_Moffstation/CCVar/CCVars.Moff.cs
Labels: S: Needs Review, size/S, S: Untriaged

#610 Death of engineering cyborg
  Resources/Locale/en-US/_Moffstation/robotics/borg_modules.ftl
  Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
Labels: Changes: No C#, size/S

#612 Memorialize Sector Umbra
  Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
  Resources/Prototypes/_Umbra/Entities/Structures/Wallmounts/Signs/posters.yml
  Resources/Textures/_Umbra/Structures/Wallmounts/posters.rsi/clouds_legit.png
  Resources/Textures/_Umbra/Structures/Wallmounts/posters.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#615 Give HoS the E-shotty back
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
Labels: Changes: No C#, size/S, S: Untriaged

#611 New borg chassis - Science frame!
  Resources/Locale/en-US/_Moffstation/borg/borg.ftl
  Resources/Locale/en-US/_Moffstation/interaction/interaction-popup-component.ftl
  Resources/Locale/en-US/_Moffstation/robotics/borg_modules.ftl
  Resources/Locale/en-US/borg/borg.ftl
  Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/Recipes/Lathes/Packs/robotics.yml
  Resources/Prototypes/Research/experimental.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/Cyborgs/borg_chassis.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/Cyborgs/borg_types.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/_Moffstation/Recipes/Lathes/robot_modules.yml
  Resources/Prototypes/borg_types.yml
  Resources/ServerInfo/Guidebook/Science/Cyborgs.xml
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/adv-anomaly-module.png
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/anomaly-module.png
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/meta.json
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/node-scanner-module.png
  Resources/Textures/_Moffstation/Mobs/Silicon/Chassis/science.rsi/borg.png
  Resources/Textures/_Moffstation/Mobs/Silicon/Chassis/science.rsi/borg_e.png
  Resources/Textures/_Moffstation/Mobs/Silicon/Chassis/science.rsi/borg_e_r.png
  Resources/Textures/_Moffstation/Mobs/Silicon/Chassis/science.rsi/borg_l.png
  Resources/Textures/_Moffstation/Mobs/Silicon/Chassis/science.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Specific/Robotics/borgmodule.rsi/icon-anomalies-adv.png
  Resources/Textures/_Moffstation/Objects/Specific/Robotics/borgmodule.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#594 Reload On The Move
  Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs
Labels: S: Needs Review, size/XS, S: Untriaged

#617 Silicon stamp!
  Resources/Locale/en-US/_Moffstation/paper/stamp-component.ftl
  Resources/Prototypes/_Moffstation/Entities/Objects/Misc/rubber_stamp.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Textures/_Moffstation/Objects/Misc/stamps.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Misc/stamps.rsi/stamp-silicon.png
Labels: S: Needs Review, Changes: No C#, size/S, Changes: Sprites

#583 Avali Racial Trait: EMP Weakness
  Content.Server/StationEvents/Events/IonStormRule.cs
  Content.Server/_Moffstation/Traits/EntitySystems/EmpVulnerableSystem.cs
  Content.Shared/_Moffstation/Traits/Components/EmpVulnerableComponent.cs
  Content.Shared/_Moffstation/Traits/EntitySystems/SharedEmpVulnerableSystem.cs
  Resources/Locale/en-US/_Moffstation/emp-vulnerable/emp-vulnerable.ftl
  Resources/Prototypes/_CD/Entities/Mobs/Species/avali.yml
Labels: S: Needs Review, S: Untriaged, size/M

#588 Re-Balance the Hypereutactic Blade and Add an Admeme Version
  Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Melee/e_sword.yml
Labels: S: Needs Review, Changes: No C#, size/S

#605 Tiny Pirate Fixes + Giving Pirate Gear Pirate Accent When Worn
  Resources/Prototypes/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Mask/pirate_gas_mask.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Melee/pirate_hook.yml
  Resources/Prototypes/_Moffstation/Roles/Antags/pirate.yml
Labels: Changes: No C#, size/S, S: Untriaged

#518 Give Resomi innate Nightvision.
  Resources/Prototypes/_Starlight/Entities/Mobs/Species/resomi.yml
  Resources/ServerInfo/_Starlight/Guidebook/Mobs/Resomi.xml
Labels: Changes: No C#, size/S, S: Untriaged

#603 Improve blade server discoverability kinda
  Content.IntegrationTests/Tests/MachineBoardTest.cs
  Content.Server/Construction/MachineFrameSystem.cs
  Content.Shared/Construction/Components/MachineBoardComponent.cs
  Content.Shared/Construction/NodeEntities/BoardNodeEntity.cs
  Content.Shared/_Moffstation/BladeServer/SharedBladeServerSystem.cs
  Content.Shared/_Moffstation/BladeServer/components.cs
  Resources/Locale/en-US/_Moffstation/blade-server/blade-server.ftl
  Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Devices/BladeServers/blade-server-frame.yml
  Resources/Prototypes/_Moffstation/Recipes/Crafting/blade_servers.yml
Labels: S: Needs Review, S: Untriaged, size/M

#625 Fixed Round starts failing
  Content.IntegrationTests/Tests/GameRules/FailAndStartPresetTest.cs
  Content.Shared/GameTicking/Components/GameRuleComponent.cs
Labels: S: Needs Review, size/XS, S: Untriaged

#626 LPO Spawns alongside other syndicate
  Resources/Prototypes/_Moffstation/Catalog/Fills/Crates/LPO.yml
  Resources/Prototypes/_Moffstation/GameRules/roundstart.yml
  Resources/Prototypes/game_presets.yml
Labels: Changes: No C#, size/S

#632 fix nightvisioncomponent test fails
  Content.Client/_Moffstation/Overlay/Systems/NightVisionSystem.cs
Labels: S: Needs Review, size/XS, S: Untriaged

#635 Make NightVision implementation better.
  Content.Client/_Moffstation/Overlay/Systems/NightVisionSystem.cs
  Content.Client/_Starlight/Overlay/BaseVisionOverlay.cs
  Content.Client/_Starlight/Overlay/NightVisionOverlay.cs
  Content.Shared/_Moffstation/Overlay/Components/NightVisionComponent.cs
Labels: S: Needs Review, size/S, S: Untriaged

#631 Remove stamina damage from borg cardbord sword
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/toys.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#640 Meteorologist Outfit Resprites
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/meteorologist.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/meteorologist.rsi/inhand-right.png
Labels: S: Needs Review, Changes: No C#, size/XS, Changes: Sprites

#623 Add painting cyborg module!
  Resources/Locale/en-US/_Moffstation/robotics/borg_modules.ftl
  Resources/Prototypes/Entities/Objects/Fun/crayons.yml
  Resources/Prototypes/Recipes/Lathes/Packs/robotics.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/_Moffstation/Objects/Tools/spray_painter.yml
  Resources/Prototypes/_Moffstation/Recipes/Lathes/robot_modules.yml
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/meta.json
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/paint-module.png
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#606 specialist-lite modules
  Resources/Prototypes/Recipes/Lathes/Packs/robotics.yml
  Resources/Prototypes/Research/civilianservices.yml
  Resources/Prototypes/Research/industrial.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/_Moffstation/Recipes/Lathes/robot_modules.yml
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/generic-cleaning-module.png
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/generic-construction-module.png
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/generic-mining-module.png
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/generic-musical-module.png
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/generic-treatment-module.png
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#613 Personal Item: Cooks-The-Meth Letter from a friend.
  Content.Client/Paper/EnvelopeSystem.cs
  Content.Shared/Paper/EnvelopeSystem.cs
  Resources/Locale/en-US/_Moffstation/personalitems/letters.ftl
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Huaqas/Cooks-the-Meth/letter.yml
Labels: Changes: No C#, size/S, S: Untriaged

#639 Roboticist & Machinist Outfits
  Resources/Prototypes/Catalog/VendingMachines/Inventories/robodrobe.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/Loadouts/Jobs/Science/scientist.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/_Moffstation/Loadouts/Non-Antags/clothing-science.yml
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-mach.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-mach.rsi/icon-open.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-mach.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-mach.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-mach.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-mach.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-mach.rsi/open-equipped-OUTERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-mach.rsi/open-inhand-left.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-mach.rsi/open-inhand-right.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-robo.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-robo.rsi/icon-open.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-robo.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-robo.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-robo.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-robo.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-robo.rsi/open-equipped-OUTERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-robo.rsi/open-inhand-left.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Coats/labcoat-robo.rsi/open-inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/machinist.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/machinist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/machinist.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/machinist.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/machinist.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/machinist.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/machinist.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/machinist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/machinist.rsi/folded-equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/machinist.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/machinist.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/machinist.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/machinist.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#643 Dug station!
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/_Moffstation/dugstation.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, Changes: Map, size/XL
