Repository moff-station/moff-station-14, pull requests merged in 2025-03, with the labels that each got.

#1 meatballs can be cooked on their own
  Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml
  Resources/Prototypes/Recipes/Construction/Graphs/food/meatball.yml
Labels: S: Needs Review

#8 Update PR guidelines
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Changes: No C#, size/S, S: Untriaged

#9 Update publishing parameters
  Tools/publish_multi_request.py
Labels: Changes: No C#, size/XS, S: Untriaged

#7 Revert low pressure damage
  Content.Shared/Atmos/Atmospherics.cs
Labels: size/XS, S: Untriaged

#10 Upstream merge 3-23-3035
  .github/workflows/benchmarks.yml
  .github/workflows/build-docfx.yml
  .github/workflows/build-map-renderer.yml
  .github/workflows/build-test-debug.yml
  .github/workflows/check-crlf.yml
  .github/workflows/publish.yml
  .github/workflows/rsi-diff.yml
  .github/workflows/test-packaging.yml
  .github/workflows/update-credits.yml
  .github/workflows/validate-rgas.yml
  .github/workflows/validate-rsis.yml
  .github/workflows/validate_mapfiles.yml
  .github/workflows/yaml-linter.yml
  Content.Client/Changelog/ChangelogTab.xaml.cs
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Changelog/Admin.yml
  Resources/Changelog/Changelog.yml
  Resources/ConfigPresets/WizardsDen/wizardsDen.toml
  Resources/Credits/GitHub.txt
  Resources/Maps/bagel.yml
  Resources/Prototypes/Catalog/Fills/Boxes/service.yml
  Resources/Prototypes/Catalog/Fills/Crates/botany.yml
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
  Resources/Prototypes/Catalog/Fills/Lockers/service.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chemvend.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/nutri.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/wallmed.yml
  Resources/Prototypes/Catalog/thief_toolbox_sets.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Clothing/Masks/masks.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Department/medical.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/drinks_bottles.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/materials.yml
  Resources/Prototypes/Entities/Mobs/NPCs/entity_tables.yml
  Resources/Prototypes/Entities/Objects/Deliveries/deliveries_tables.yml
  Resources/Prototypes/Entities/Objects/Deliveries/package_rare_tables.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/Entities/Objects/Specific/chemistry-bottles.yml
  Resources/Prototypes/Entities/Objects/Tools/handheld_mass_scanner.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
  Resources/Prototypes/Procedural/salvage_loot.yml
  Resources/Prototypes/Procedural/salvage_rewards.yml
  Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
  Resources/ServerInfo/Guidebook/Service/Botany.xml
  Resources/migration.yml
Labels: S: Untriaged, size/M, Changes: Map, Changes: UI

#11 Ch buff
  Resources/Prototypes/Reagents/toxins.yml
Labels: Changes: No C#, size/S, S: Untriaged

#13 CVar for disabling Role Item Loadout Timers
  Content.Client/Lobby/LobbyUIController.cs
  Content.IntegrationTests/PoolManager.Cvars.cs
  Content.Shared/CCVar/CCVars.Game.cs
  Content.Shared/Preferences/Loadouts/Effects/JobRequirementLoadoutEffect.cs
  Resources/ConfigPresets/Build/development.toml
Labels: size/S, S: Untriaged

#14 Upstream merge 3-24-2025
  Content.IntegrationTests/Tests/Embedding/EmbedTest.cs
  Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs
  Content.Server/Chat/Systems/SpeakOnTriggerSystem.cs
  Content.Shared/Fluids/Components/EvaporationComponent.cs
  Content.Shared/Projectiles/SharedProjectileSystem.cs
  Content.Shared/SubFloor/SharedTrayScannerSystem.cs
  Content.Shared/SubFloor/TrayScannerUserComponent.cs
  Resources/Changelog/Changelog.yml
  Resources/Maps/Shuttles/cargo_relic.yml
  Resources/Maps/Shuttles/emergency_relic.yml
  Resources/Maps/relic.yml
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Mobs/base.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Maps/relic.yml
  Resources/Textures/Objects/Devices/pda.rsi/id_overlay_wide.png
  Resources/Textures/Objects/Devices/pda.rsi/light_overlay_wide.png
  Resources/Textures/Objects/Devices/pda.rsi/meta.json
Labels: S: Untriaged, Changes: Sprites, Changes: Map, size/XL

#15 Added Colorful Light Boxes
  Resources/Prototypes/_Moffstation/Catalog/Cargo/cargo_service.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Boxes/general.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Crates/service.yml
Labels: S: Needs Review, Changes: No C#, size/S

#5 Custom changelog "Mofflog" backend changes
  Resources/Changelog/Mofflog.yml
  Resources/Changelog/MofflogAdmin.yml
  Resources/Locale/en-US/changelog/changelog-window.ftl
  Tools/actions_changelogs_since_last_run.py
Labels: Changes: No C#, size/S, S: Untriaged

#6 Ranger Hardsuit port
  Resources/Prototypes/_Moffstation/Catalog/Fills/Lockers/suit_storage.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Head/hardsuit_helmets.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/security-ranger.rsi/icon-flash.png
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/security-ranger.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/security-ranger.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/security-ranger.rsi/off-equipped-HELMET-vox.png
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/security-ranger.rsi/off-equipped-HELMET.png
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/security-ranger.rsi/on-equipped-HELMET-vox.png
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/security-ranger.rsi/on-equipped-HELMET.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Hardsuits/security-ranger.rsi/equipped-OUTERCLOTHING-vox.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Hardsuits/security-ranger.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Hardsuits/security-ranger.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Hardsuits/security-ranger.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Hardsuits/security-ranger.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/OuterClothing/Hardsuits/security-ranger.rsi/meta.json
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#17 upd changelog manually
  Resources/Changelog/Mofflog.yml
  Resources/Changelog/MofflogAdmin.yml
Labels: Changes: No C#, size/S, S: Untriaged

#18 Criminal Records Console status locale fix
  Content.Client/CriminalRecords/CriminalRecordsConsoleWindow.xaml.cs
  Resources/Locale/en-US/_Harmony/criminal-records/criminal-records.ftl
Labels: size/S, S: Untriaged, Changes: UI

#19 Skip loading character records for silicons
  Resources/Prototypes/Roles/Jobs/Science/borg.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged

#21 Streamer Lawset
  Resources/Locale/en-US/_Moffstation/station-laws/laws.ftl
  Resources/Prototypes/_Moffstation/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/_Moffstation/silicon-laws.yml
  Resources/Prototypes/silicon-laws.yml
Labels: Changes: No C#, size/S, S: Untriaged

#22 Decouple Lights from Toggleable Visuals (and headphone music notes bugfix)
  Content.Client/Light/HandheldLightSystem.cs
  Content.Client/Toggleable/ToggleableLightVisualsSystem.cs
  Content.Server/Atmos/EntitySystems/FlammableSystem.cs
  Content.Shared/Light/Components/ItemTogglePointLightComponent.cs
  Content.Shared/Light/EntitySystems/ItemTogglePointLightSystem.cs
  Content.Shared/Light/SharedHandheldLightSystem.cs
  Content.Shared/Toggleable/ToggleActionEvent.cs
  Content.Shared/Toggleable/ToggleableLightVisuals.cs
  Content.Shared/Weapons/Melee/EnergySword/EnergySwordSystem.cs
  Content.Shared/Weapons/Misc/SharedTetherGunSystem.cs
  Resources/Prototypes/Entities/Clothing/Head/base_clothinghead.yml
  Resources/Prototypes/Entities/Clothing/Head/hardhats.yml
  Resources/Prototypes/Entities/Objects/Misc/fluff_lights.yml
  Resources/Prototypes/Entities/Objects/Tools/decoys.yml
  Resources/Prototypes/Entities/Objects/Tools/flashlights.yml
  Resources/Prototypes/Entities/Objects/Tools/lantern.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
Labels: size/S, S: Untriaged

#24 Make warops admin-only
  Resources/Prototypes/Roles/Antags/nukeops.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#25 lower playercount requirements for nukies and zombies
  Resources/Prototypes/GameRules/roundstart.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged
