Repository moff-station/moff-station-14, pull requests merged in 2025-07, with the labels that each got.

#336 Blood Brothers Updates
  Content.Server/_Harmony/GameTicking/Rules/BloodBrotherRuleSystem.cs
  Content.Shared/_Harmony/BloodBrothers/Components/InitialBloodBrotherComponent.cs
  Resources/Locale/en-US/_Harmony/prototypes/roles/antags.ftl
  Resources/Prototypes/_Harmony/GameRules/subgamemodes.yml
  Resources/Prototypes/_Harmony/Objectives/bloodbrother.yml
  Resources/Prototypes/_Harmony/Objectives/objectiveGroups.yml
  Resources/Prototypes/_Harmony/Roles/Antags/bloodbrother.yml
  Resources/Prototypes/_Moffstation/Objectives/bloodbrother.yml
  Resources/Prototypes/_Moffstation/Objectives/objectiveGroups.yml
Labels: S: Needs Review, size/S, S: Untriaged, Changes: Audio

#339 Revert "Revert "added ability to pick cat ears and cat tail as human""
  Resources/Prototypes/Species/human.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#332 Gun Game Improvements
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Content.Server/_Moffstation/GameTicking/Rules/Components/GunGameRuleComponent.cs
  Content.Server/_Moffstation/GameTicking/Rules/GunGameRuleSystem.cs
  Resources/Maps/_Moffstation/Nonstations/Dock.yml
  Resources/Maps/_Moffstation/Nonstations/Dust2.yml
  Resources/Prototypes/_Moffstation/GameRules/gungame.yml
  Resources/Prototypes/_Moffstation/Maps/Pools/gungame.yml
  Resources/Prototypes/_Moffstation/Maps/arenas.yml
  Resources/Prototypes/_Moffstation/game_presets.yml
Labels: S: Needs Review, S: Untriaged, Changes: Map, size/XL

#340 Mothroaches
  Resources/Prototypes/Catalog/Fills/Crates/npc.yml
  Resources/Prototypes/GameRules/pests.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/NPCs/mothroaches.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/rehydrateable.yml
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/0-equipped-HELMET.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/icon.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/mothroach-moving.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/mothroach.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/mothroach_dead.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/mothroach_lazy.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/deathshead.rsi/mothroach_sleep.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/0-equipped-HELMET.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/icon.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/mothroach-moving.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/mothroach.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/mothroach_dead.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/mothroach_lazy.png
  Resources/Textures/_Moffstation/Mobs/Animals/mothroach/rosy.rsi/mothroach_sleep.png
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites, Changes: Map

#343 Update metacomming rules for better clarity
  Resources/Locale/en-US/_Moffstation/guidebook/guides.ftl
  Resources/Prototypes/_Moffstation/Guidebook/rules.yml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffMetacomming.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR2Metagaming.xml
Labels: S: Needs Review, Changes: No C#, size/S

#312 Paper Signing
  Content.Client/Paper/UI/PaperWindow.xaml.cs
  Content.Client/Paper/UI/StampCollection.xaml.cs
  Content.Client/Paper/UI/StampWidget.xaml.cs
  Content.Client/_Moffstation/Paper/UI/ForgeSignatureBoundUserInterface.cs
  Content.Client/_Moffstation/Paper/UI/ForgeSignatureWindow.xaml
  Content.Client/_Moffstation/Paper/UI/ForgeSignatureWindow.xaml.cs
  Content.Shared/Paper/PaperSystem.cs
  Content.Shared/Paper/StampComponent.cs
  Content.Shared/_Moffstation/Paper/Components/ForgeSignatureComponent.cs
  Content.Shared/_Moffstation/Paper/Systems/ForgeSignatureSystem.cs
  Resources/Locale/en-US/_Umbra/paper/paper-component.ftl
  Resources/Prototypes/Entities/Objects/Misc/pen.yml
Labels: S: Untriaged, size/M, Changes: UI

#352 ERT gamerules
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Locale/en-US/_Moffstation/station-events/ert.ftl
  Resources/Maps/_Moffstation/PreCrewed/dart.yml
  Resources/Maps/_Moffstation/PreCrewed/shuttle-nt-equilibrium.yml
  Resources/Maps/_Moffstation/PreCrewed/shuttle-nt-grimebreaker.yml
  Resources/Maps/_Moffstation/PreCrewed/shuttle-nt-lockup.yml
  Resources/Maps/_Moffstation/PreCrewed/shuttle-nt-vacator-cburn.yml
  Resources/Maps/_Moffstation/PreCrewed/shuttle-nt-vacator-deathsquad.yml
  Resources/Maps/_Moffstation/PreCrewed/shuttle-nt-vacator.yml
  Resources/Maps/_Moffstation/PreCrewed/shuttle-tbe-artificer.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/Player/Spawners/ert.yml
  Resources/Prototypes/_Moffstation/GameRules/ert.yml
Labels: S: Needs Review, Changes: No C#, Changes: Map, size/XL

#356 Added Swat Shoes To Hacked ClothesMate Manager Inventory
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
Labels: Changes: No C#, S: Untriaged

#335 Give Borgs Neck Slots
  Content.Server/Silicons/Borgs/BorgSwitchableTypeSystem.cs
  Content.Shared/DisplacementMap/DisplacementData.cs
  Content.Shared/Inventory/InventoryComponent.cs
  Content.Shared/Inventory/InventorySystem.Slots.cs
  Content.Shared/Silicons/Borgs/BorgTypePrototype.cs
  Resources/Prototypes/InventoryTemplates/borg.yml
  Resources/Prototypes/borg_types.yml
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/displacement.aseprite
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/engineer.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/engineer.rsi/neck.png
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/generic.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/generic.rsi/neck.png
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/janitor.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/janitor.rsi/neck.png
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/medical.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/medical.rsi/neck.png
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/mining.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Silicon/Displacements/mining.rsi/neck.png
  Tools/SS14 Aseprite Plugins/Displacement Map Flip.lua
  Tools/SS14 Aseprite Plugins/Displacement Map Shift.lua
  Tools/SS14 Aseprite Plugins/Displacement Map Visualizer.lua
Labels: S: Needs Review, Changes: No C#, size/M, Changes: Sprites

#351 Master merge 2025-07-011
  Content.Client/Damage/Systems/StaminaSystem.cs
  Content.Client/SprayPainter/SprayPainterSystem.cs
  Content.Client/SprayPainter/UI/SprayPainterGroup.xaml.cs
  Content.Client/SprayPainter/UI/SprayPainterWindow.xaml.cs
  Content.Client/Storage/Visualizers/EntityStorageVisualizerSystem.cs
  Content.Client/Stunnable/StunSystem.cs
  Content.Server/SprayPainter/SprayPainterSystem.cs
  Content.Shared/Damage/Components/StaminaComponent.cs
  Content.Shared/Damage/Systems/SharedStaminaSystem.cs
  Content.Shared/SprayPainter/Components/PaintableComponent.cs
  Content.Shared/SprayPainter/Components/PaintedComponent.cs
  Content.Shared/SprayPainter/Components/SprayPainterComponent.cs
  Content.Shared/SprayPainter/Prototypes/AirlockDepartmentsPrototype.cs
  Content.Shared/SprayPainter/Prototypes/AirlockGroupPrototype.cs
  Content.Shared/SprayPainter/Prototypes/PaintableGroupPrototype.cs
  Content.Shared/SprayPainter/SharedSprayPainterSystem.cs
  Content.Shared/SprayPainter/SprayPainterAmmoSystem.cs
  Content.Shared/SprayPainter/SprayPainterEvents.cs
  Content.Shared/Stunnable/SharedStunSystem.Visualizer.cs
  Content.Shared/Stunnable/SharedStunSystem.cs
  Content.Shared/Stunnable/StunVisualsComponent.cs
  Content.Shared/Stunnable/StunnedComponent.cs
  Resources/Changelog/Changelog.yml
  Resources/Changelog/Maps.yml
  Resources/Locale/en-US/spray-painter/spray-painter.ftl
  Resources/Maps/bagel.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Entities/Mobs/Player/clone.yml
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Mobs/base.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/airlocks.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/base_structureclosets.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/wall_lockers.yml
  Resources/Prototypes/Entities/Structures/Storage/Crates/base_structurecrates.yml
  Resources/Prototypes/Paintables/categories.yml
  Resources/Prototypes/Paintables/crate_groups.yml
  Resources/Prototypes/Paintables/locker_groups.yml
  Resources/Textures/Mobs/Effects/stunned.rsi/meta.json
  Resources/Textures/Mobs/Effects/stunned.rsi/stunned.png
  Resources/Textures/Structures/Wallmounts/turret_controls.rsi/base.png
  Resources/Textures/Structures/Wallmounts/turret_controls.rsi/lethal.png
  Resources/Textures/Structures/Wallmounts/turret_controls.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/turret_controls.rsi/safe.png
  Resources/Textures/Structures/Wallmounts/turret_controls.rsi/stun.png
  Resources/Textures/Structures/Wallmounts/turret_controls.rsi/wires.png
Labels: S: Untriaged, Changes: Sprites, Changes: Map, Changes: UI, size/XL

#359 Improved my personal item
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPin.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPin.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPinInversed.rsi/equipped-NECK.png
Labels: Changes: No C#, S: Untriaged, Changes: Sprites

#358 Open Ended Objective improvements
  Content.Server/_Moffstation/Objectives/Components/DisruptionObjectiveComponent.cs
  Content.Server/_Moffstation/Objectives/Components/GreytextObjectiveComponent.cs
  Content.Server/_Moffstation/Objectives/Components/LocationObjectiveComponent.cs
  Content.Server/_Moffstation/Objectives/Components/PickDepartmentObjectiveComponent.cs
  Content.Server/_Moffstation/Objectives/Components/PickRandomDepartmentComponent.cs
  Content.Server/_Moffstation/Objectives/Components/PickRoomObjectiveComponent.cs
  Content.Server/_Moffstation/Objectives/Components/PickSpecificDepartmentComponent.cs
  Content.Server/_Moffstation/Objectives/Components/TargetDepartmentComponent.cs
  Content.Server/_Moffstation/Objectives/Components/TargetDepartmentOverrideComponent.cs
  Content.Server/_Moffstation/Objectives/Systems/DisruptionObjectiveSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/GreytextObjectiveSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/LocationObjectiveSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/PickDepartmentObjectiveSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/PickObjectiveDepartmentSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/PickRoomObjectiveSystem.cs
  Content.Server/_Moffstation/Objectives/Systems/TargetDepartmentSystem.cs
  Resources/Locale/en-US/_Moffstation/objectives/conditions/open-objective.ftl
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Prototypes/_Harmony/Objectives/objectiveGroups.yml
  Resources/Prototypes/_Moffstation/Objectives/bloodbrother.yml
  Resources/Prototypes/_Moffstation/Objectives/objectiveGroups.yml
  Resources/Prototypes/_Moffstation/Objectives/open_objectives.yml
Labels: S: Needs Review, S: Untriaged, size/M

#367 Add the Ruffler's Mask
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/freianofvoid/Remia/remiaphoto.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/freianofvoid/Chris_Ruffler/rufflermask.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Chris_Ruffler/rufflermask.rsi/equipped-MASK-hamster.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Chris_Ruffler/rufflermask.rsi/equipped-MASK-reptilian.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Chris_Ruffler/rufflermask.rsi/equipped-MASK-vox.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Chris_Ruffler/rufflermask.rsi/equipped-MASK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Chris_Ruffler/rufflermask.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Chris_Ruffler/rufflermask.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Chris_Ruffler/rufflermask.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Chris_Ruffler/rufflermask.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#368 Listening Outpost Map + Cabinet Fills
  Resources/Maps/_Moffstation/Nonstations/LPO.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Cabinets/filing_cabinets.yml
Labels: S: Needs Review, Changes: No C#, Changes: Map, size/XL

#369 Pinktext Autosubmit
  Content.Client/_DV/CustomObjectiveSummary/CustomObjectiveSummaryUIController.cs
  Content.Client/_DV/CustomObjectiveSummary/CustomObjectiveSummaryWindow.xaml.cs
Labels: size/S, Changes: UI

#370 Talvi Figurine
  Resources/Locale/en-US/_Moffstation/datasets/figurines.ftl
  Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/_Moffstation/Datasets/figurines.yml
  Resources/Prototypes/_Moffstation/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/figurine_boxes.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/figurines.yml
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/talvi.png
Labels: Changes: No C#, S: Untriaged, Changes: Sprites

#373 Fix up rules
  Resources/Prototypes/_Moffstation/Guidebook/rules.yml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffMetashield.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR2Metagaming.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR3Powergaming.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR4RP.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR9Prisoners.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffRules.xml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#372 Engineering Sunglasses
  Resources/Locale/en-US/_Moffstation/recipes/tags.ftl
  Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Eyes/glasses.yml
  Resources/Prototypes/_Moffstation/Recipes/Construction/Graphs/Clothing/mesonsunglasses.yml
  Resources/Prototypes/_Moffstation/Recipes/Construction/Graphs/clothing.yml
  Resources/Prototypes/_Moffstation/tags.yml
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/equipped-EYES-arachnid.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/equipped-EYES-dog.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/equipped-EYES-hamster.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/equipped-EYES-moth.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/equipped-EYES-secdog.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/equipped-EYES.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/mesonsunglasses.rsi/meta.json
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#317 Adds BallisticAmmoSelfRefillerComponent
  Content.Server/Weapons/Ranged/Systems/GunSystem.AutoFire.cs
  Content.Server/Weapons/Ranged/Systems/GunSystem.Ballistic.cs
  Content.Server/Weapons/Ranged/Systems/GunSystem.cs
  Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs
  Content.Shared/_Moffstation/Weapons/Ranged/Components/BallisticAmmoSelfRefillerComponent.cs
  Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
Labels: S: Needs Review, S: Untriaged, size/M

#380 Rules requirement based on total playercount
  Content.Server/GameTicking/GameTicker.RoundFlow.cs
  Content.Server/GameTicking/Rules/GameRuleSystem.cs
  Content.Server/GameTicking/Rules/SecretRuleSystem.cs
  Content.Shared/CCVar/CCVars.Game.cs
Labels: S: Needs Review, size/S, S: Untriaged
