Repository moff-station/moff-station-14, pull requests merged in 2025-04, with the labels that each got.

#32 Allow clown, mime, and borg loadouts to have customized names
  Content.Server/Station/Systems/StationSpawningSystem.cs
  Resources/Prototypes/Loadouts/role_loadouts.yml
Labels: size/S, S: Untriaged

#35 update unclear comment in JobRequirementLoadoutEffect.cs
  Content.Shared/Preferences/Loadouts/Effects/JobRequirementLoadoutEffect.cs
Labels: size/XS, S: Untriaged

#30 Added personal items tab to loadout
  Content.Shared/Preferences/Loadouts/Effects/GroupLoadoutEffect.cs
  Content.Shared/_Umbra/Preferences/Loadouts/Effects/PersonalItemLoadoutEffect.cs
  Resources/Locale/en-US/_Umbra/preferences/loadouts.ftl
  Resources/Prototypes/Loadouts/role_loadouts.yml
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/katiewristband.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/katiewristband.rsi/equipped-HAND.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/katiewristband.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/katiewristband.rsi/meta.json
Labels: S: Needs Review, S: Untriaged, size/M, Changes: Sprites

#29 Gigs's personal item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/gigsshaker.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/gigsshaker.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/gigsshaker.rsi/meta.json
Labels: Changes: No C#, size/S, Changes: Sprites

#33 Scribbles's Personal Item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/scribblesplushie.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/scribblesplushie.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/scribblesplushie.rsi/lizard-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Items/scribblesplushie.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/scribblesplushie.rsi/plushielizard-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/scribblesplushie.rsi/plushielizard-inhand-right.png
Labels: Changes: No C#, size/S, Changes: Sprites

#27 Ryker's personal item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/rykerpen.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/rykerpen.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/rykerpen.rsi/pen-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/rykerpen.rsi/pen-inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/rykerpen.rsi/pen.png
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#36 Krakatoa's Personal Item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/KrakatoaCloak.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/krakatoacloak.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/krakatoacloak.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/krakatoacloak.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/krakatoacloak.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/krakatoacloak.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#39 Seikret's Photo
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/seikretphoto.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/seikretphoto.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/seikretphoto.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#28 Darnell's personal item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/darnelllighter.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/darnelllighter.rsi/closed.png
  Resources/Textures/_Moffstation/PersonalItems/Items/darnelllighter.rsi/inhand-left-flame.png
  Resources/Textures/_Moffstation/PersonalItems/Items/darnelllighter.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/darnelllighter.rsi/inhand-right-flame.png
  Resources/Textures/_Moffstation/PersonalItems/Items/darnelllighter.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/darnelllighter.rsi/lighter_flame.png
  Resources/Textures/_Moffstation/PersonalItems/Items/darnelllighter.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/darnelllighter.rsi/open.png
  Resources/Textures/_Moffstation/PersonalItems/Items/darnelllighter.rsi/top.png
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#40 Add personal item guidelines
  PERSONALITEMS.md
Labels: Changes: No C#, S: Untriaged, size/M

#42 Deli's Pearl
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/JamiMyst/Delivers-Through-Storms/redpearl.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/JamiMyst/Delivers-Through-Storms/redpearl.rsi/equipped-MASK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/JamiMyst/Delivers-Through-Storms/redpearl.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/JamiMyst/Delivers-Through-Storms/redpearl.rsi/meta.json
Labels: Changes: No C#, Changes: Sprites

#44 Tempfix blocked interactions with unpowered items
  Content.Shared/Silicons/StationAi/SharedStationAiSystem.Held.cs
Labels: size/S, S: Untriaged

#46 Add Deli's pearl to the loadouts
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#31 Eclipse Sunshade's Personal Item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Kento/eclipsetoyshotgun.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun.rsi/bolt-open.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun.rsi/equipped-BACKPACK.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun_inhands_64x.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun_inhands_64x.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun_inhands_64x.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun_inhands_64x.rsi/wielded-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun_inhands_64x.rsi/wielded-inhand-right.png
Labels: Changes: No C#, size/S, Changes: Sprites

#38 Frost Winter's Personal Item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/FrostWinters/Frost_Winters/frostmedicalwebbing.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FrostWinters/Frost_Winters/frostmedicalwebbing.rsi/equipped-BELT.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FrostWinters/Frost_Winters/frostmedicalwebbing.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FrostWinters/Frost_Winters/frostmedicalwebbing.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FrostWinters/Frost_Winters/frostmedicalwebbing.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FrostWinters/Frost_Winters/frostmedicalwebbing.rsi/meta.json
Labels: Changes: No C#, size/S, Changes: Sprites

#47 moffroach migration
  Resources/Prototypes/GameRules/pests.yml
Labels: Changes: No C#, size/S

#48 Personal item fixes
  Content.Shared/_Umbra/Preferences/Loadouts/Effects/PersonalItemLoadoutEffect.cs
  Resources/Prototypes/_Moffstation/PersonalItems/Items/BulletKin/darnelllighter.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Centronias/rykerpen.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/JamiMyst/Delivers-through-Storms/redpearl.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.rsi/closed.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.rsi/inhand-left-flame.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.rsi/inhand-right-flame.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.rsi/lighter_flame.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.rsi/open.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.rsi/top.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.rsi/zippo-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.rsi/zippo-inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Centronias/Ryker_Ximenez/rykerpen.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/Centronias/Ryker_Ximenez/rykerpen.rsi/pen-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Centronias/Ryker_Ximenez/rykerpen.rsi/pen-inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Centronias/Ryker_Ximenez/rykerpen.rsi/pen.png
Labels: size/S, S: Untriaged, Changes: Sprites

#52 Update personal items
  PERSONALITEMS.md
Labels: Changes: No C#, size/S, S: Untriaged

#51 Personal Item: Cooks-the-Meth Plushie
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Huaqas/Cooks-the-Meth/Plushiescooksplushie.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/Huaqas/Cooks-the-Meth/cooksplushie.rsi/cooks-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Huaqas/Cooks-the-Meth/cooksplushie.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/Huaqas/Cooks-the-Meth/cooksplushie.rsi/plushie_cooks.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Huaqas/Cooks-the-Meth/cooksplushie.rsi/plushielizard-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Huaqas/Cooks-the-Meth/cooksplushie.rsi/plushielizard-inhand-right.png
Labels: S: Needs Review, Changes: No C#, size/S, Changes: Sprites

#54 Personal Item: Sean's bedsheet
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Exbedio/Sean_Exbdo/seansheet.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Exbedio/Sean_Exbdo/seansheet.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Exbedio/Sean_Exbdo/seansheet.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Exbedio/Sean_Exbdo/seansheet.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#55 Personal Item: Sapphire's ampule
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/SapphireMaris/Sapphire_Maris/sapphireampule.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/SapphireMaris/Sapphire_Maris/sapphireampule.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/SapphireMaris/Sapphire_Maris/sapphireampule.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/SapphireMaris/Sapphire_Maris/sapphireampule.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/SapphireMaris/Sapphire_Maris/sapphireampule.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/SapphireMaris/Sapphire_Maris/sapphireampule.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#59 update PERSONALITEMS.md
  PERSONALITEMS.md
Labels: Changes: No C#, size/XS, S: Untriaged

#60 update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Changes: No C#, size/S, S: Untriaged

#63 Musicians can set their names in loadouts now.
  Resources/Prototypes/Loadouts/role_loadouts.yml
Labels: Changes: No C#, S: Untriaged

#62 Disable warops player limit
  Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
Labels: size/XS, S: Untriaged

#37 Corrected some stuff with personalItems
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Altimus/Scribbles-the-Notes/scribblesplushie.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/BulletKin/Darnell_Flett/darnelllighter.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Centronias/Ryker_Ximenez/rykerpen.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Failed/Works-Many-Gigs/gigsshaker.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/MythicalGrubbin/Seikret_Lissenger/seikretphoto.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/DR_D1NGO/Krakatoa_Jones/KrakatoaCloak.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/JamiMyst/Delivers-through-Storms/redpearl.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Snowlili/Katie_Fae/katiewristband.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Zebadica/Cinnabar_Furrofin/cinnabarmask.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/Altimus/Scribbles-the-Notes/scribblesplushie.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Altimus/Scribbles-the-Notes/scribblesplushie.rsi/lizard-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Altimus/Scribbles-the-Notes/scribblesplushie.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/Altimus/Scribbles-the-Notes/scribblesplushie.rsi/plushielizard-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Altimus/Scribbles-the-Notes/scribblesplushie.rsi/plushielizard-inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/DR_D1NGO/Krakatoa_Jones/krakatoacloak.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/DR_D1NGO/Krakatoa_Jones/krakatoacloak.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/DR_D1NGO/Krakatoa_Jones/krakatoacloak.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/DR_D1NGO/Krakatoa_Jones/krakatoacloak.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/DR_D1NGO/Krakatoa_Jones/krakatoacloak.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Snowlili/Katie_Fae/katiewristband.rsi/equipped-HAND.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Snowlili/Katie_Fae/katiewristband.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Snowlili/Katie_Fae/katiewristband.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#64 Personal Item: Fred's watch
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/equipped-HAND.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_0.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_1.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_10.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_11.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_2.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_3.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_4.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_5.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_6.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_7.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_8.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/hours_9.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_0.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_1.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_10.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_11.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_2.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_3.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_4.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_5.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_6.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_7.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_8.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/FriedFCC/Fred_Neuman/fredwatch.rsi/minutes_9.png
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#66 Halfed the ammo of disabler weapons
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Labels: Changes: No C#, size/XS

#68 Added .50 shotgun pellet rounds to the uplink
  Resources/Locale/en-US/_Moffstation/store/uplink-catalog.ftl
  Resources/Prototypes/_Moffstation/Catalog/uplink_catalog.yml
Labels: S: Needs Review, Changes: No C#, size/S

#67 Easier improv shotgun
  Resources/Prototypes/Recipes/Crafting/Graphs/improvised/improvised_shotgun_shell.yml
Labels: Changes: No C#, size/S, S: Untriaged

#61 Personal Item: Lilith's Guitar
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/LillianMothette/Lilith_Mothette/lilithguitar.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/LillianMothette/Lilith_Mothette/lilithguitar.rsi/equipped-BACKPACK.png
  Resources/Textures/_Moffstation/PersonalItems/Items/LillianMothette/Lilith_Mothette/lilithguitar.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_Moffstation/PersonalItems/Items/LillianMothette/Lilith_Mothette/lilithguitar.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/LillianMothette/Lilith_Mothette/lilithguitar.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/LillianMothette/Lilith_Mothette/lilithguitar.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/LillianMothette/Lilith_Mothette/lilithguitar.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/LillianMothette/Lilith_Mothette/lilithguitar.rsi/wielded-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/LillianMothette/Lilith_Mothette/lilithguitar.rsi/wielded-inhand-right.png
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#69 Port CD's Height Slider from Umbra
  Content.Client/Humanoid/HumanoidAppearanceSystem.cs
  Content.Client/Lobby/UI/HumanoidProfileEditor.xaml
  Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
  Content.IntegrationTests/Tests/Preferences/ServerDbSqliteTests.cs
  Content.Server.Database/Model.cs
  Content.Server/Database/ServerDbBase.cs
  Content.Shared/Humanoid/HumanoidAppearanceComponent.cs
  Content.Shared/Humanoid/NamingSystem.cs
  Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
  Content.Shared/Humanoid/SharedHumanoidAppearanceSystem.cs
  Content.Shared/Preferences/HumanoidCharacterProfile.cs
  Resources/Locale/en-US/_Moffstation/preferences/ui/humanoid-profile-editor.ftl
Labels: enhancement, S: Needs Review, size/M, Changes: UI

#71 Weapon Resizing
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/watergun.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/flare_gun.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M

#53 Cyborg rebalance
  Resources/Prototypes/Entities/Markers/Spawners/Random/Department/science.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Objects/Devices/holoprojectors.yml
  Resources/Prototypes/Entities/Objects/Materials/Sheets/glass.yml
  Resources/Prototypes/Entities/Objects/Materials/Sheets/metal.yml
  Resources/Prototypes/Entities/Objects/Materials/Sheets/other.yml
  Resources/Prototypes/Entities/Objects/Materials/parts.yml
  Resources/Prototypes/Entities/Objects/Misc/fire_extinguisher.yml
  Resources/Prototypes/Entities/Objects/Specific/Janitorial/spray.yml
  Resources/Prototypes/Entities/Objects/Specific/Janitorial/trashbag.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/Entities/Objects/Specific/Salvage/ore_bag.yml
  Resources/Prototypes/Entities/Objects/Specific/chemistry-vials.yml
  Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
  Resources/Prototypes/Entities/Objects/Tools/bucket.yml
  Resources/Prototypes/Entities/Objects/Tools/gps.yml
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
  Resources/Prototypes/Recipes/Lathes/Packs/robotics.yml
  Resources/Prototypes/Recipes/Lathes/robotics.yml
  Resources/Prototypes/Research/civilianservices.yml
  Resources/Prototypes/Research/experimental.yml
  Resources/Prototypes/Research/industrial.yml
  Resources/Prototypes/borg_types.yml
  Resources/ServerInfo/Guidebook/Science/Cyborgs.xml
  Resources/Textures/Interface/Actions/actions_borg.rsi/adv-chem-module.png
  Resources/Textures/Interface/Actions/actions_borg.rsi/adv-mining-module.png
  Resources/Textures/Interface/Actions/actions_borg.rsi/chem-module.png
  Resources/Textures/Interface/Actions/actions_borg.rsi/meta.json
  Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/icon-chem.png
  Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/icon-mining-adv.png
  Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/meta.json
  Resources/migration.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#76 Amber updates
  Resources/Maps/amber.yml
  Resources/Prototypes/Parallaxes/amber.yml
  Resources/Textures/Parallaxes/Asteroids.png
  Resources/Textures/Parallaxes/attributions.yml
  Resources/Textures/Parallaxes/debris_large.png
  Resources/Textures/Parallaxes/debris_small.png
  Resources/map_attributions.txt
Labels: Changes: No C#, S: Untriaged, Changes: Map, size/XL

#82 Added Cargo Tech Lobby Screen
  Resources/Prototypes/_Moffstation/lobbyscreens.yml
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/_Moffstation/LobbyScreens/attributions.yml
  Resources/Textures/_Moffstation/LobbyScreens/cargo-tech-lobby.png
  Resources/Textures/_Moffstation/LobbyScreens/cargo-tech-lobby.png.yml
Labels: Changes: No C#, size/S, S: Untriaged

#72 Drozd hyperburst
  Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#65 Cargo Packing Error (fka "Stowaways") Event
  Content.Server/Cargo/Systems/CargoSystem.Orders.cs
  Content.Server/_Moffstation/StationEvents/Components/CargoPackingErrorRuleComponent.cs
  Content.Server/_Moffstation/StationEvents/Events/CargoPackingErrorRule.cs
  Content.Server/_Moffstation/Storage/Components/SpawnOnNextOpenComponent.cs
  Content.Server/_Moffstation/Storage/EntitySystems/SpawnOnNextOpenSystem.cs
  Content.Shared/_Moffstation/Cargo/Events/CargoOrderFulfilledEvent.cs
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Tools/decoys.yml
  Resources/Prototypes/_Moffstation/GameRules/cargo_packing_error.yml
Labels: S: Needs Review, S: Untriaged, size/M

#84 Post-Departmental Economy Telepad Research Adjustment
  Resources/Prototypes/Research/civilianservices.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#79 Slight revert to previous Disabler + DisablerSMG nerf.
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Labels: Changes: No C#, size/XS

#77 Height slider default
  Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
Labels: size/XS, S: Untriaged, Changes: UI

#86 Roundstart Variation for Solar Panels
  Content.Server/_Moffstation/GameTicking/Rules/VariationPass/Components/ReplacementMarkers/SolarPanelReplacementMarkerComponent.cs
  Content.Server/_Moffstation/GameTicking/Rules/VariationPass/Components/SolarPanelReplaceVariationPassComponent.cs
  Content.Server/_Moffstation/GameTicking/Rules/VariationPass/SolarPanelReplaceVariationPassSystem.cs
  Resources/Prototypes/Entities/Structures/Power/Generation/solar.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/_Moffstation/GameRules/variation.yml
Labels: size/S, S: Untriaged

#70 Antag loadouts and customizable names
  Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
  Content.Server/Antag/AntagSelectionSystem.cs
  Content.Shared/Clothing/LoadoutSystem.cs
  Resources/Locale/en-US/_Moffstation/preferences/loadout-groups.ftl
  Resources/Prototypes/Entities/Mobs/Player/human.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/Roles/Antags/nukeops.yml
  Resources/Prototypes/Roles/Jobs/Fun/wizard_startinggear.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Backpacks/AntagStarterGear/operative_backpacks.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Back/syndicateSatchel.yml
  Resources/Prototypes/_Moffstation/Loadouts/Antags/nukeops.yml
  Resources/Prototypes/_Moffstation/Loadouts/Antags/wizard.yml
  Resources/Prototypes/_Moffstation/Loadouts/antag_loadout_groups.yml
  Resources/Prototypes/_Moffstation/Loadouts/antag_loadouts.yml
  Resources/Textures/_Moffstation/Clothing/Back/Satchels/syndicate.rsi/equipped-BACKPACK.png
  Resources/Textures/_Moffstation/Clothing/Back/Satchels/syndicate.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Back/Satchels/syndicate.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Back/Satchels/syndicate.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Back/Satchels/syndicate.rsi/meta.json
Labels: S: Needs Review, S: Untriaged, size/M, Changes: Sprites, Changes: UI

#88 Makes dwarves stout again
  Content.Client/Humanoid/HumanoidAppearanceSystem.cs
  Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
  Resources/Prototypes/Species/dwarf.yml
Labels: size/S, S: Untriaged

#90 added Brad Bucket lobby screen
  Resources/Prototypes/_Moffstation/lobbyscreens.yml
  Resources/Textures/_Moffstation/LobbyScreens/attributions.yml
  Resources/Textures/_Moffstation/LobbyScreens/brad-bucket-lobby.webp
  Resources/Textures/_Moffstation/LobbyScreens/brad-bucket-lobby.webp.yml
Labels: Changes: No C#, size/S, S: Untriaged

#85 Action buttons can be used within the action window.
  Content.Client/UserInterface/Systems/Actions/ActionUIController.cs
Labels: S: Needs Review, size/S, S: Untriaged

#89 Added Last Call lobby screen
  Resources/Prototypes/_Moffstation/lobbyscreens.yml
  Resources/Textures/_Moffstation/LobbyScreens/attributions.yml
  Resources/Textures/_Moffstation/LobbyScreens/last-call-lobby.png
  Resources/Textures/_Moffstation/LobbyScreens/last-call-lobby.png.yml
Labels: Changes: No C#, size/S, S: Untriaged

#91 Resilient Grenades
  Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml
  Resources/Prototypes/Entities/Objects/Weapons/Throwable/projectile_grenades.yml
Labels: Changes: No C#, size/M

#93 Added Awana Group Selfie lobby screen
  Resources/Prototypes/_Moffstation/lobbyscreens.yml
  Resources/Textures/_Moffstation/LobbyScreens/attributions.yml
  Resources/Textures/_Moffstation/LobbyScreens/awana-group-selfie.webp
  Resources/Textures/_Moffstation/LobbyScreens/awana-group-selfie.webp.yml
Labels: Changes: No C#, size/S, S: Untriaged

#95 changed playercounts
  Resources/Prototypes/Maps/elkridge.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/packed.yml
  Resources/Prototypes/Maps/reach.yml
Labels: Changes: No C#, size/XS, S: Untriaged, Changes: Map

#96 Solar Panel Variation Pass Fix
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/_Moffstation/GameRules/variation.yml
Labels: Changes: No C#

#98 Poster - Five Hundred Mothroaches
  Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
  Resources/Prototypes/_Moffstation/Entities/Structures/Wallmounts/Signs/posters.yml
  Resources/Textures/_Moffstation/Structures/Wallmounts/posters.rsi/five_hundred_mothroaches.png
  Resources/Textures/_Moffstation/Structures/Wallmounts/posters.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, Changes: Sprites

#97 Revert #32
  Content.Server/Station/Systems/StationSpawningSystem.cs
  Resources/Prototypes/Loadouts/role_loadouts.yml
Labels: size/S, S: Untriaged

#100 Kylie's personal item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/meganerobot/Kylie_Guess/KylieUniform.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/meganerobot/Kylie_Guess/kylieuniform.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/meganerobot/Kylie_Guess/kylieuniform.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/meganerobot/Kylie_Guess/kylieuniform.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/meganerobot/Kylie_Guess/kylieuniform.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/meganerobot/Kylie_Guess/kylieuniform.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, Changes: Sprites

#81 Tania's Personal Items
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Compilatron/shared/stationblueprints.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Compilatron/Tania_Buttersworth/backtentacles.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Compilatron/Tania_Buttersworth/backtentacles.rsi/equipped-BACKPACK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Compilatron/Tania_Buttersworth/backtentacles.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Compilatron/Tania_Buttersworth/backtentacles.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#103 Revert "Fix inability to engage with economic Cargonia (#36668)"
  Content.Server/Cargo/Systems/CargoSystem.Funds.cs
  Content.Server/Cargo/Systems/CargoSystem.Orders.cs
  Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
  Content.Server/Cargo/Systems/CargoSystem.cs
  Content.Server/Delivery/DeliverySystem.cs
  Content.Shared/Cargo/SharedCargoSystem.cs
Labels: size/S, S: Untriaged

#104 Added basic rules
  Content.Shared/CCVar/CCVars.Server.cs
  Resources/Prototypes/_Moffstation/Guidebook/rules.yml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffRules.xml
Labels: size/S, S: Untriaged

#106 Some additional cosmetics
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/Loadouts/Non-Antags/clothing-common.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#108 Bring back slime water damage
  Resources/Prototypes/Entities/Mobs/Species/slime.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#87 New antag: Pirates
  Resources/Locale/en-US/_Moffstation/preferences/loadout-groups.ftl
  Resources/Locale/en-US/_Moffstation/random-metadata/random-metadata-formats.ftl
  Resources/Locale/en-US/_Moffstation/roles/antags.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
  Resources/Prototypes/Roles/Antags/pirate.yml
  Resources/Prototypes/_Moffstation/Entities/Markers/Spawners/ghost_roles.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/Player/pirates.yml
  Resources/Prototypes/_Moffstation/GameRules/pirates.yml
  Resources/Prototypes/_Moffstation/Loadouts/Antags/pirates.yml
  Resources/Prototypes/_Moffstation/Loadouts/antag_loadout_groups.yml
  Resources/Prototypes/_Moffstation/Loadouts/antag_loadouts.yml
  Resources/Prototypes/_Moffstation/Roles/Antags/pirate.yml
  Resources/Prototypes/_Moffstation/Roles/MindRoles/mind_roles.yml
  Resources/Textures/_Moffstation/Objects/Weapons/Melee/e_cutlass.rsi/e_cutlass.png
  Resources/Textures/_Moffstation/Objects/Weapons/Melee/e_cutlass.rsi/e_cutlass_blade.png
  Resources/Textures/_Moffstation/Objects/Weapons/Melee/e_cutlass.rsi/inhand-left-blade.png
  Resources/Textures/_Moffstation/Objects/Weapons/Melee/e_cutlass.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Objects/Weapons/Melee/e_cutlass.rsi/inhand-right-blade.png
  Resources/Textures/_Moffstation/Objects/Weapons/Melee/e_cutlass.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Objects/Weapons/Melee/e_cutlass.rsi/meta.json
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#107 Thieves can innately pickpocket
  Content.Shared/Strip/Components/ThievingComponent.cs
  Content.Shared/Strip/ThievingSystem.cs
  Content.Shared/_Moffstation/Strip/Components/ThievingComponent.cs
  Resources/Locale/en-US/_Moffstation/alerts/alerts.ftl
  Resources/Locale/en-US/_Moffstation/guidebook/guides.ftl
  Resources/Prototypes/Alerts/alerts.yml
  Resources/Prototypes/GameRules/subgamemodes.yml
  Resources/Prototypes/Roles/Antags/thief.yml
  Resources/Prototypes/_Moffstation/Guidebook/rules.yml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR4Metashield.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffMetashieldChanges.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffRules.xml
  Resources/Textures/_Moffstation/Interface/Alerts/stealthy.rsi/meta.json
  Resources/Textures/_Moffstation/Interface/Alerts/stealthy.rsi/stealthy-off.png
  Resources/Textures/_Moffstation/Interface/Alerts/stealthy.rsi/stealthy-on.png
Labels: S: Needs Review, size/M, Changes: Sprites

#110 Add network link to requisition digi-board
  Resources/Prototypes/Entities/Objects/Misc/paper.yml
Labels: Changes: No C#, size/S

#114 Gives smile an internal inventory and ID card slot
  Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
  Resources/Prototypes/_Moffstation/InventoryTemplates/headid_inventory_template.yml
Labels: Changes: No C#, size/S, S: Untriaged

#112 Adds Sawa-Tar's personal skirt
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Davyei/Sawa-Tar/SawaTarUniform.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Davyei/Sawa-Tar/sawataruniform.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Davyei/Sawa-Tar/sawataruniform.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Davyei/Sawa-Tar/sawataruniform.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Davyei/Sawa-Tar/sawataruniform.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Davyei/Sawa-Tar/sawataruniform.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Davyei/Sawa-Tar/sawataruniform.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#116 Slime damage
  Resources/Prototypes/Entities/Mobs/NPCs/slimes.yml
  Resources/Prototypes/Entities/Mobs/Species/slime.yml
Labels: Changes: No C#, size/XS

#118 Added Peedee personal item.
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/peedeeavatar-dance.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/peedeeavatar-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/peedeeavatar-equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/peedeeavatar-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/peedeeavatar-inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/peedeeavatar-storage.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/peedeeavatar.png
Labels: Changes: No C#, size/M, Changes: Sprites

#115 Medical wrench
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Tools/medical_wrench.yml
  Resources/Textures/_Moffstation/Objects/Tools/medical_wrench.rsi/equipped-BELT.png
  Resources/Textures/_Moffstation/Objects/Tools/medical_wrench.rsi/icon.png
  Resources/Textures/_Moffstation/Objects/Tools/medical_wrench.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Objects/Tools/medical_wrench.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Objects/Tools/medical_wrench.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Tools/medical_wrench.rsi/storage.png
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#113 New Centcomm
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Content.Server/Shuttles/Components/StationCentcommComponent.cs
  Resources/Maps/_Harmony/centcomm.yml
  Resources/Prototypes/Maps/centcomm.yml
Labels: Changes: Map, size/XL

#101 Squeakify moff sfx
  Resources/Audio/_Moffstation/Voice/Talk/attributions.yml
  Resources/Audio/_Moffstation/Voice/Talk/moth.ogg
  Resources/Audio/_Moffstation/Voice/Talk/moth_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/moth_exclaim.ogg
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/Species/moth.yml
  Resources/Prototypes/_Moffstation/Voice/speech_sounds.yml
Labels: size/S, S: Untriaged

#119 Hack to make record consoles work again
  Content.Server/_CD/Records/Consoles/CharacterRecordConsoleSystem.cs
Labels: S: Needs Review, size/S, S: Untriaged

#121 Depthead loadouts
  Resources/Locale/en-US/_Moffstation/preferences/loadout-groups.ftl
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/Loadouts/Non-Antags/clothing-medical.yml
Labels: Changes: No C#, size/M

#123 ACTUALLY IMPLEMENTING Depthead loadouts
  Resources/Prototypes/Loadouts/role_loadouts.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#124 Peedee Personal Update
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/peedeeavatar-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Chartman95/Peedee/peedeeavatar.rsi/peedeeavatar-equipped-NECK.png
Labels: Changes: No C#, size/XS, Changes: Sprites

#125 Small revert to exactly how text is entered in the PDA ringer
  Content.Client/PDA/Ringer/RingtoneMenu.xaml.cs
Labels: size/S, S: Untriaged, Changes: UI

#126 Asher Ying's personal item
  Resources/Prototypes/_Moffstation/PersonalItems/Items/MythicalGrubbin/Asher_Ying/asherhealthanalyzer.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/MythicalGrubbin/Asher_Ying/asherhealthanalyzer.rsi/analyzer-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/MythicalGrubbin/Asher_Ying/asherhealthanalyzer.rsi/analyzer-inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/MythicalGrubbin/Asher_Ying/asherhealthanalyzer.rsi/analyzer.png
  Resources/Textures/_Moffstation/PersonalItems/Items/MythicalGrubbin/Asher_Ying/asherhealthanalyzer.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/MythicalGrubbin/Asher_Ying/asherhealthanalyzer.rsi/meta.json
Labels: Changes: No C#, size/S, Changes: Sprites

#120 Fix escape pods
  Content.Server/Shuttles/Components/DockingComponent.cs
  Content.Server/Shuttles/Components/EscapePodComponent.cs
  Content.Server/Shuttles/Systems/DockingSystem.Shuttle.cs
  Content.Server/Shuttles/Systems/EmergencyShuttleSystem.Console.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
  Resources/Maps/_Harmony/centcomm.yml
  Resources/Prototypes/_Moffstation/Entities/Structures/Doors/Airlocks/access.yml
  Resources/Prototypes/_Moffstation/tags.yml
Labels: S: Untriaged, size/M, Changes: Map

#128 Disable station rotation
  Content.Server/Maps/GameMapPrototype.cs
Labels: size/XS, S: Untriaged

#130 CentComm - Updates
  Resources/Maps/_Harmony/centcomm.yml
Labels: Changes: No C#, S: Untriaged, Changes: Map

#111 hardsuit buffs
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#131 Crew Figurines
  Resources/Locale/en-US/_Moffstation/datasets/figurines.ftl
  Resources/Prototypes/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/games.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/arcades.yml
  Resources/Prototypes/_Moffstation/Datasets/figurines.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/figurine_boxes.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/figurines.yml
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/awana.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/brad-bucket.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/brad.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/cassiel.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/cinnabar.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/darnell.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/delivers.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/echiara.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/eclipse.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/fig-box.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/fred.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/gigs.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/iris.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/jelob.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/jobs.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/katie.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/krakatoa.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/kylie.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/lilith.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/nyxilath.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/peedee.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/rareel.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/sapphire.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/sawa.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/scribbles.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/sean.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/seikret.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/siliconwing.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/southbridge.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/strawberry.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/tania.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/tar.png
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#132 Deptheadloadouts patch: I forgot the CE's bag group
  Resources/Prototypes/Loadouts/loadout_groups.yml
Labels: Changes: No C#, S: Untriaged

#135 Additional Centcomm improvements
  Resources/Maps/_Harmony/centcomm.yml
Labels: Changes: No C#, S: Untriaged, Changes: Map, size/L

#134 Made execution Centcomm only
  Resources/Prototypes/_Moffstation/Guidebook/rules.yml
  Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffRules.xml
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffSpaceLawChanges.xml
Labels: Changes: No C#, size/S

#140 Added inhand visuals for slime plushie
  Resources/Prototypes/Entities/Objects/Fun/toys.yml
  Resources/Textures/_Moffstation/Objects/Fun/slimeplush.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Objects/Fun/slimeplush.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Objects/Fun/slimeplush.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Fun/slimeplush.rsi/plushie_slime.png
Labels: Changes: No C#, Changes: Sprites

#139 Reapply "Add new color turtlenecks in WinterDrobe" (#36983)
  Resources/Prototypes/Catalog/VendingMachines/Inventories/winterdrobe.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/color_turtlenecks.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/color_turtlenecks_skirt.yml
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/skirt-equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/skirt-icon.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/skirt-inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/color_turtle.rsi/skirt-inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/trousers-equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/trousers-icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/trousers-inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/color_turtle.rsi/trousers-inhand-right.png
Labels: Changes: No C#, S: Untriaged, Changes: Sprites, size/L

#133 Handheld radio upgrade + red phone comms
  Content.Server/Radio/Components/RadioSpeakerComponent.cs
  Content.Server/Radio/EntitySystems/RadioDeviceSystem.cs
  Resources/Maps/elkridge.yml
  Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
  Resources/Prototypes/Entities/Objects/Devices/radio.yml
  Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_misc.yml
Labels: S: Needs Review, S: Untriaged, size/M, Changes: Map

#141 Adding personal items for Nyx and Iris
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Nyxilath/Nyxilath_Steelewing/nyxilathring.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Tezzaide/Iris_Steelewing/irisring.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nyxilath/Nyxilath_Steelewing/nyxilathring.rsi/equipped-HAND.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nyxilath/Nyxilath_Steelewing/nyxilathring.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Nyxilath/Nyxilath_Steelewing/nyxilathring.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Tezzaide/Iris_Steelewing/irisring.rsi/equipped-HAND.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Tezzaide/Iris_Steelewing/irisring.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Tezzaide/Iris_Steelewing/irisring.rsi/meta.json
Labels: Changes: No C#, size/S, Changes: Sprites
