Repository moff-station/moff-station-14, pull requests merged in 2025-06, with the labels that each got.

#236 Vent Critter Hordes
  Content.Server/StationEvents/Components/VentCrittersRuleComponent.cs
  Content.Server/StationEvents/Events/VentCrittersRule.cs
  Content.Server/_Moffstation/StationEvents/Components/VentCrittersRuleComponent.cs
  Content.Server/_Moffstation/StationEvents/Events/VentCrittersRule.cs
  Resources/Locale/en-US/_Moffstation/station-events/vent-critters.ftl
  Resources/Locale/en-US/station-events/events/vent-critters.ftl
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/pests.yml
Labels: S: Needs Review, S: Untriaged, size/M

#260 Fix Hugbot Sprite
  Resources/Textures/Mobs/Silicon/Bots/hugbot.rsi/hugbot.png
  Resources/Textures/Mobs/Silicon/Bots/hugbot.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#257 Nanochat
  Content.Client/Access/UI/AgentIDCardBoundUserInterface.cs
  Content.Client/Access/UI/AgentIDCardWindow.xaml
  Content.Client/Access/UI/AgentIDCardWindow.xaml.cs
  Content.Client/CartridgeLoader/Cartridges/LogProbeUi.cs
  Content.Client/CartridgeLoader/Cartridges/LogProbeUiFragment.xaml
  Content.Client/CartridgeLoader/Cartridges/LogProbeUiFragment.xaml.cs
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatEntry.xaml
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatEntry.xaml.cs
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatLogEntry.xaml
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatLogEntry.xaml.cs
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatLookupView.xaml
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatLookupView.xaml.cs
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatMessageBubble.xaml
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatMessageBubble.xaml.cs
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatUi.cs
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml
  Content.Client/_CD/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml.cs
  Content.Client/_CD/CartridgeLoader/Cartridges/NewChatPopup.xaml
  Content.Client/_CD/CartridgeLoader/Cartridges/NewChatPopup.xaml.cs
  Content.Client/_CD/NanoChat/NanoChatSystem.cs
  Content.Server/Access/Systems/AgentIDCardSystem.cs
  Content.Server/CartridgeLoader/Cartridges/LogProbeCartridgeComponent.cs
  Content.Server/CartridgeLoader/Cartridges/LogProbeCartridgeSystem.NanoChat.cs
  Content.Server/CartridgeLoader/Cartridges/LogProbeCartridgeSystem.cs
  Content.Server/_CD/CartridgeLoader/Cartridges/NanoChatCartridgeComponent.cs
  Content.Server/_CD/CartridgeLoader/Cartridges/NanoChatCartridgeSystem.cs
  Content.Server/_CD/NanoChat/NanoChatSystem.cs
  Content.Shared/Access/SharedAgentIDCardSystem.cs
  Content.Shared/CartridgeLoader/Cartridges/LogProbeUiState.cs
  Content.Shared/_CD/CartridgeLoader/Cartridges/NanoChatUiMessageEvent.cs
  Content.Shared/_CD/CartridgeLoader/Cartridges/NanoChatUiState.cs
  Content.Shared/_CD/NanoChat/NanoChatCardComponent.cs
  Content.Shared/_CD/NanoChat/SharedNanoChatSystem.cs
  Resources/Locale/en-US/_CD/access/components/agent-id-card-component.ftl
  Resources/Locale/en-US/_CD/cartridge-loader/cartridges.ftl
  Resources/Locale/en-US/_CD/nanochat/components/nanochat-card-component.ftl
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/_CD/Entities/Objects/Devices/cartridges.yml
  Resources/Prototypes/_CD/name_identifier_groups.yml
  Resources/Textures/_CD/Interface/VerbIcons/ATTRIBUTION.txt
  Resources/Textures/_CD/Interface/VerbIcons/bell.svg
  Resources/Textures/_CD/Interface/VerbIcons/bell.svg.png
  Resources/Textures/_CD/Interface/VerbIcons/bell_muted.png
  Resources/Textures/_CD/Interface/VerbIcons/hamburger_icon.svg.png
  Resources/Textures/_CD/Misc/program_icons.rsi/meta.json
  Resources/Textures/_CD/Misc/program_icons.rsi/nanochat.png
  Resources/Textures/_CD/Objects/Devices/cartridge.rsi/cart-chat.png
  Resources/Textures/_CD/Objects/Devices/cartridge.rsi/meta.json
Labels: S: Needs Review, S: Untriaged, Changes: Sprites, Changes: UI, size/L

#266 Pirate Captain hardsuit fix
  Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/piratecaptain.rsi/icon-flash.png
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/piratecaptain.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/piratecaptain.rsi/off-equipped-HELMET.png
  Resources/Textures/_Moffstation/Clothing/Head/Hardsuits/piratecaptain.rsi/on-equipped-HELMET.png
Labels: Changes: No C#, size/XS, S: Untriaged, Changes: Sprites

#262 Early Merge - Trans Station
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/tram2.yml
  Resources/Prototypes/Maps/tram2.yml
Labels: S: Needs Review, S: Untriaged, Changes: Map, size/XL

#255 Minor ghostroles (Carp, spiders, etc) don't have raffles
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
  Resources/Prototypes/Entities/Mobs/NPCs/slimes.yml
Labels: Changes: No C#, size/S, S: Untriaged

#267 Big Iron
  Resources/Locale/en-US/_Moffstation/objectives/conditions/steal-target-groups.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Prototypes/Recipes/Lathes/Packs/security.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Ammunition/Boxes/magnum.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Ammunition/Cartridges/magnum.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Ammunition/SpeedLoaders/magnum.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Projectiles/projectiles.yml
  Resources/Prototypes/_Moffstation/Objectives/stealTargetGroups.yml
  Resources/Prototypes/_Moffstation/Objectives/traitor.yml
  Resources/Prototypes/_Moffstation/Recipes/Lathes/ammo.yml
  Resources/Prototypes/_Moffstation/tags.yml
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/Casings/big_iron_casing.rsi/base-spent.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/Casings/big_iron_casing.rsi/base.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/Casings/big_iron_casing.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/Casings/big_iron_casing.rsi/tip.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/base-1.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/base-2.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/base-3.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/base-4.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/base-5.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/base-6.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/base.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/inhand-left-ammo.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/inhand-left-mag.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/inhand-left-stripe.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/inhand-right-ammo.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/inhand-right-mag.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/inhand-right-stripe.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Ammunition/SpeedLoaders/big_iron_speed_loader.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Revolvers/big_iron.rsi/base.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Revolvers/big_iron.rsi/equipped-BELT.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Revolvers/big_iron.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Revolvers/big_iron.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Revolvers/big_iron.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Revolvers/big_iron.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#268 Updated Centcomm and Arrivals
  Resources/Maps/_Harmony/centcomm.yml
  Resources/Maps/_Umbra/Misc/terminal.yml
Labels: Changes: No C#, S: Untriaged, Changes: Map

#274 Fedora Buff
  Resources/Textures/Clothing/Head/Hats/brownfedora.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hats/brownfedora.rsi/inhand-left.png
  Resources/Textures/Clothing/Head/Hats/brownfedora.rsi/inhand-right.png
  Resources/Textures/Clothing/Head/Hats/brownfedora.rsi/meta.json
  Resources/Textures/Clothing/Head/Hats/greyfedora.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hats/greyfedora.rsi/inhand-left.png
  Resources/Textures/Clothing/Head/Hats/greyfedora.rsi/inhand-right.png
  Resources/Textures/Clothing/Head/Hats/greyfedora.rsi/meta.json
Labels: Changes: No C#, size/XS, S: Untriaged, Changes: Sprites

#270 Waterjug Update
  Resources/Maps/Waterjug.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Decals/flora.yml
  Resources/Prototypes/Entities/Objects/Misc/tiles.yml
  Resources/Prototypes/Tiles/floors.yml
Labels: Changes: No C#, Changes: Map

#275 Russian accent
  Resources/Locale/en-US/_CD/traits/traits.ftl
  Resources/Prototypes/_CD/Traits/speech.yml
Labels: Changes: No C#

#271 Pinktexting
  Content.Client/UserInterface/Systems/Character/CharacterUIController.cs
  Content.Client/_DV/CustomObjectiveSummary/CustomObjectiveSummaryUIController.cs
  Content.Client/_DV/CustomObjectiveSummary/CustomObjectiveSummaryWindow.xaml
  Content.Client/_DV/CustomObjectiveSummary/CustomObjectiveSummaryWindow.xaml.cs
  Content.Server/GameTicking/GameTicker.RoundFlow.cs
  Content.Server/Objectives/ObjectivesSystem.cs
  Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
  Content.Server/_DV/CustomObjectiveSummary/CustomObjectiveSummarySystem.cs
  Content.Shared.Database/LogType.cs
  Content.Shared/_DV/CustomObjectiveSummary/CustomObjectiveSummaryComponent.cs
  Content.Shared/_DV/CustomObjectiveSummary/CustomObjectiveSummeryEvents.cs
  Resources/Locale/en-US/_DV/customobjectivesummary/customobjectivesummary.ftl
Labels: size/M, Changes: UI

#263 Player Figurines 3: Return of the GI: Joe
  Resources/Locale/en-US/_Moffstation/datasets/figurines.ftl
  Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/_Moffstation/Datasets/figurines.yml
  Resources/Prototypes/_Moffstation/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/figurine_boxes.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/figurines.yml
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/brisbane.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/brisbanebighat.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/cooks.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/faces.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/lightsseeker.png
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/samantha.png
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#279 Fix bonux CMO backpack loadouts
  Resources/Prototypes/_Moffstation/Loadouts/Non-Antags/clothing-medical.yml
Labels: Changes: No C#, size/S, S: Untriaged

#278 Squeaks's Hampter Personal Item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/privatemumbles/Squeaks/squeakshampter.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Squeaks/squeakshampter.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Squeaks/squeakshampter.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Squeaks/squeakshampter.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Squeaks/squeakshampter.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#280 Exclude Pirate shuttles from being returned by StationSystem.GetStationInMap
  Content.Server/Station/Systems/StationSystem.cs
  Content.Server/_Moffstation/GameTicking/Rules/Components/PiratesRuleComponent.cs
  Content.Shared/_Moffstation/Pirate/Components/PirateShuttleComponent.cs
  Resources/Prototypes/_Moffstation/Entities/Stations/pirate.yml
Labels: size/S, S: Untriaged

#283 Increase Big Iron damage and switch its default fill to disabler rounds
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Projectiles/projectiles.yml
Labels: Changes: No C#, size/XS

#282 Adds Cory's personal item
  Resources/Prototypes/_Moffstation/PersonalItems/Items/privatemumbles/Cory_Graves/coryclipboard.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/privatemumbles/Squeaks/squeakshampter.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Cory_Graves/coryclipboard.rsi/clipboard.png
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Cory_Graves/coryclipboard.rsi/clipboard_paper.png
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Cory_Graves/coryclipboard.rsi/clipboard_pen.png
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Cory_Graves/coryclipboard.rsi/equipped-BELT.png
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Cory_Graves/coryclipboard.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Cory_Graves/coryclipboard.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/privatemumbles/Cory_Graves/coryclipboard.rsi/meta.json
Labels: Changes: No C#, S: Untriaged, Changes: Sprites

#288 Medical sunglasses
  Resources/Locale/en-US/_Moffstation/recipes/tags.ftl
  Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Eyes/glasses.yml
  Resources/Prototypes/_Moffstation/Recipes/Construction/Graphs/Clothing/medsunglasses.yml
  Resources/Prototypes/_Moffstation/Recipes/Construction/Graphs/clothing.yml
  Resources/Prototypes/_Moffstation/tags.yml
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/medsunglasses.rsi/equipped-EYES-arachnid.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/medsunglasses.rsi/equipped-EYES-hamster.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/medsunglasses.rsi/equipped-EYES-moth.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/medsunglasses.rsi/equipped-EYES-secdog.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/medsunglasses.rsi/equipped-EYES.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/medsunglasses.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/medsunglasses.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/medsunglasses.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Eyes/Glasses/medsunglasses.rsi/meta.json
Labels: Changes: No C#, size/S, Changes: Sprites

#293 Removed water jug
  Resources/Prototypes/Maps/Pools/default.yml
Labels: S: Needs Review, Changes: No C#, Changes: Map

#297 Fix Figurine spelling error and adjust rarity for RARE figurine.
  Resources/Locale/en-US/_Moffstation/datasets/figurines.ftl
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/figurine_boxes.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#294 Add guards so that map vote rollovers can't throw
  Content.Server/Maps/GameMapManager.cs
Labels: size/XS, S: Untriaged

#303 Allow latejoining to station
  Content.Server/_CD/Spawners/ArrivalsSpawnPointSystem.cs
  Content.Shared/CCVar/CCVars.Shuttle.cs
  Resources/Locale/en-US/_CD/job/job-description.ftl
Labels: size/S, S: Untriaged

#304 Arrivals Battery Recharge
  Content.Server/Shuttles/Components/ArrivalsShuttleComponent.cs
  Content.Server/Shuttles/Systems/ArrivalsSystem.cs
Labels: S: Needs Review, size/S, S: Untriaged

#205 New centcomm loadouts
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Roles/Jobs/CentComm/official.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/_Moffstation/Roles/Jobs/CentComm/official.yml
  Resources/Textures/Markers/jobs.rsi/centcom.png
  Resources/Textures/Markers/jobs.rsi/centcomexec.png
  Resources/Textures/Markers/jobs.rsi/centcomofficer.png
  Resources/Textures/Markers/jobs.rsi/centcomrep.png
  Resources/Textures/Markers/jobs.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#307 Skies-of-Sunshine's Personal Item (e g g)
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Vivenshadow/Skies-Of-Sunshine/skiesegg.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/Vivenshadow/Skies-of-Sunshine/skiesegg.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Vivenshadow/Skies-of-Sunshine/skiesegg.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Vivenshadow/Skies-of-Sunshine/skiesegg.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Vivenshadow/Skies-of-Sunshine/skiesegg.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#309 Moonlight Galileo figurine
  Resources/Locale/en-US/_Moffstation/datasets/figurines.ftl
  Resources/Prototypes/_Moffstation/Datasets/figurines.yml
  Resources/Prototypes/_Moffstation/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/figurine_boxes.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/figurines.yml
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Fun/figurines.rsi/moonlight.png
Labels: Changes: No C#, size/S, Changes: Sprites

#314 Chits!
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/discount.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/snack.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/winterdrobe.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/food_snacks.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/trash.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Consumable/Food/snacks.yml
  Resources/Textures/_Moffstation/Objects/Consumable/Food/snacks.rsi/chits-trash.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/snacks.rsi/chits.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/snacks.rsi/meta.json
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#306 Borg Plush
  Resources/Prototypes/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/Entities/Objects/Decoration/present.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/arcades.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Toboe/Sigerthe-Rei/lilbuddy.yml
  Resources/Textures/_Moffstation/Objects/Fun/toys.rsi/borg-equipped-HELMET.png
  Resources/Textures/_Moffstation/Objects/Fun/toys.rsi/borg-inhand-left.png
  Resources/Textures/_Moffstation/Objects/Fun/toys.rsi/borg-inhand-right.png
  Resources/Textures/_Moffstation/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Fun/toys.rsi/plushie_borg.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Toboe/Sigerthe-Rei/lilbuddy.rsi/lilbuddy-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Toboe/Sigerthe-Rei/lilbuddy.rsi/lilbuddy-inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Toboe/Sigerthe-Rei/lilbuddy.rsi/lilbuddy-inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Toboe/Sigerthe-Rei/lilbuddy.rsi/lilbuddy.png
  Resources/Textures/_Moffstation/PersonalItems/Items/Toboe/Sigerthe-Rei/lilbuddy.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#324 Added PD Phone Home as a lobby screen.
  Resources/Prototypes/_Moffstation/lobbyscreens.yml
  Resources/Textures/_Moffstation/LobbyScreens/attributions.yml
  Resources/Textures/_Moffstation/LobbyScreens/pd-phone-home.png
  Resources/Textures/_Moffstation/LobbyScreens/pd-phone-home.yml
Labels: Changes: No C#, S: Untriaged

#321 Grenade fragments travel farther
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/grenade.yml
Labels: Changes: No C#, size/XS

#320 Reworks the Big Iron into a Svalinn-type gun with its own power cell
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Recipes/Lathes/Packs/security.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Ammunition/Boxes/magnum.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Ammunition/Cartridges/magnum.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Ammunition/SpeedLoaders/magnum.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Ammunition/powercells.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
  Resources/Prototypes/_Moffstation/Recipes/Lathes/ammo.yml
  Resources/Prototypes/_Moffstation/tags.yml
Labels: Changes: No C#, S: Untriaged, size/M

#323 Updated stamina resistance to match upstream and be far simplier
  Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Objects/Weapons/security.yml
  Resources/Prototypes/Research/arsenal.yml
Labels: Changes: No C#, S: Untriaged, size/M

#245 Revert "added ability to pick cat ears and cat tail as human"
  Resources/Prototypes/Species/human.yml
Labels: Changes: No C#, S: Untriaged

#325 The Mask Lobby Art
  Resources/Prototypes/_Moffstation/lobbyscreens.yml
  Resources/Textures/_Moffstation/LobbyScreens/attributions.yml
  Resources/Textures/_Moffstation/LobbyScreens/the-mask.png
  Resources/Textures/_Moffstation/LobbyScreens/the-mask.yml
Labels: Changes: No C#, size/S

#301 Mercenary Loadouts
  Resources/Locale/en-US/_Moffstation/ghost/roles/ghost-role-component.ftl
  Resources/Locale/en-US/_Moffstation/job/job-description.ftl
  Resources/Locale/en-US/_Moffstation/job/job-names.ftl
  Resources/Locale/en-US/_Moffstation/random-metadata/random-metadata-formats.ftl
  Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/_Moffstation/Roles/Jobs/Wildcards/mercenary.yml
  Resources/Prototypes/_Moffstation/Roles/play_time_trackers.yml
  Resources/Textures/_Moffstation/Markers/jobs.rsi/mercenary.png
  Resources/Textures/_Moffstation/Markers/jobs.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#327 Added Space Frolick lobby art.
  Resources/Prototypes/_Moffstation/lobbyscreens.yml
  Resources/Textures/_Moffstation/LobbyScreens/attributions.yml
  Resources/Textures/_Moffstation/LobbyScreens/space-frolick.webp
  Resources/Textures/_Moffstation/LobbyScreens/space-frolick.yml
Labels: Changes: No C#, S: Untriaged

#329 Fix some paintable tank issues
  Content.Client/_Moffstation/Atmos/Visualizers/GasTankVisualizerSystem.cs
  Content.Shared/_Moffstation/Atmos/Components/GasTankVisualsComponent.cs
  Content.Shared/_Moffstation/Atmos/Visuals/GasTankColorValues.cs
  Resources/Prototypes/Entities/Objects/Tools/gas_tanks.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Tools/gas_tanks.yml
  Resources/Textures/Objects/Tanks/emergency.rsi/equipped-SUITSTORAGE-stripe-low.png
  Resources/Textures/Objects/Tanks/emergency.rsi/equipped-SUITSTORAGE-stripe-middle.png
  Resources/Textures/Objects/Tanks/emergency_double.rsi/equipped-SUITSTORAGE-stripe-low.png
  Resources/Textures/Objects/Tanks/emergency_double.rsi/equipped-SUITSTORAGE-stripe-middle.png
  Resources/Textures/Objects/Tanks/emergency_extended.rsi/equipped-SUITSTORAGE-stripe-low.png
  Resources/Textures/Objects/Tanks/emergency_extended.rsi/equipped-SUITSTORAGE-stripe-middle.png
  Resources/Textures/Objects/Tanks/tank.rsi/equipped-SUITSTORAGE-stripe-low.png
Labels: S: Untriaged, size/M, Changes: Sprites

#328 Added Dawn of the Xenoborgs Lobby art.
  Resources/Prototypes/_Moffstation/lobbyscreens.yml
  Resources/Textures/_Moffstation/LobbyScreens/attributions.yml
  Resources/Textures/_Moffstation/LobbyScreens/xenoborg-lobby.png
  Resources/Textures/_Moffstation/LobbyScreens/xenoborg-lobby.yml
Labels: Changes: No C#, size/S, S: Untriaged

#334 Pirate captain hardsuit sprite fix
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged
