Repository moff-station/moff-station-14, pull requests merged in 2025-08, with the labels that each got.

#381 Borg plush noise fix
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/toys.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#365 Syndicate Listening Outpost
  Content.Client/Medical/CrewMonitoring/CrewMonitoringBoundUserInterface.cs
  Content.Server/_CD/Records/Consoles/CharacterRecordConsoleComponent.cs
  Content.Server/_CD/Records/Consoles/CharacterRecordConsoleSystem.cs
  Content.Server/_Moffstation/GameTicking/Rules/Components/ListeningOutpostRuleComponent.cs
  Content.Server/_Moffstation/GameTicking/Rules/Components/LoadGridRuleComponent.cs
  Content.Server/_Moffstation/GameTicking/Rules/ListeningOutpostRuleSystem.cs
  Content.Server/_Moffstation/GameTicking/Rules/LoadGridRuleSystem.cs
  Content.Server/_Moffstation/Medical/CrewMonitoring/LongRangeCrewMonitorSystem.cs
  Content.Server/_Moffstation/Roles/SyndicateSpyRoleComponent.cs
  Content.Shared/_Moffstation/Medical/CrewMonitoring/LongRangeCrewMonitorComponent.cs
  Resources/Locale/en-US/_Moffstation/roles/antags.ftl
  Resources/Maps/_Moffstation/Nonstations/LPO.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Entities/Structures/Machines/crew_monitor_server.yml
  Resources/Prototypes/Entities/Structures/Machines/surveillance_camera_routers.yml
  Resources/Prototypes/Entities/Structures/Machines/wireless_surveillance_camera.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Cabinets/filing_cabinets.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Crates/LPO.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/_Moffstation/Entities/Markers/Spawners/Conditional/syndicate.yml
  Resources/Prototypes/_Moffstation/Entities/Markers/Spawners/pirate.yml
  Resources/Prototypes/_Moffstation/Entities/Markers/Spawners/syndicate.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/Player/syndicate.yml
  Resources/Prototypes/_Moffstation/Entities/Structures/Machines/computers.yml
  Resources/Prototypes/_Moffstation/GameRules/listening_outpost.yml
  Resources/Prototypes/_Moffstation/Loadouts/antag_loadouts.yml
  Resources/Prototypes/_Moffstation/Roles/Antags/syndicate.yml
  Resources/Prototypes/_Moffstation/Roles/MindRoles/mind_roles.yml
Labels: S: Needs Review, S: Untriaged, Changes: Sprites, Changes: Map, size/L

#387 LPO Tweaks
  Resources/Maps/_Moffstation/Nonstations/LPO.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Cabinets/filing_cabinets.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Crates/LPO.yml
  Resources/Prototypes/_Moffstation/GameRules/listening_outpost.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Map

#344 Mandatory beach episode
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/_Moffstation/water_vapour.yml
  Resources/Prototypes/_Moffstation/Maps/water_vapour.yml
  Resources/Prototypes/_Moffstation/Parallaxes/water.yml
  Resources/Textures/_Moffstation/Tiles/Planet/water.png
Labels: S: Needs Review, Changes: No C#, Changes: Map, size/XL

#385 More detailed loadouts for gun game
  Resources/Prototypes/_Moffstation/GameRules/gungame.yml
  Resources/Prototypes/_Moffstation/Roles/Jobs/Fun/gungame.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M

#375 Cams and holopads for cc
  Resources/Maps/_Harmony/centcomm.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, Changes: Map, size/XL

#276 Add Collective Minds (Ported Starlight PRs # 69, # 70)
  Content.Client/CharacterInfo/CharacterInfoSystem.cs
  Content.Client/Chat/Managers/ChatManager.cs
  Content.Client/Chat/Managers/IChatManager.cs
  Content.Client/UserInterface/Systems/Character/CharacterUIController.cs
  Content.Client/UserInterface/Systems/Character/Windows/CharacterWindow.xaml
  Content.Client/UserInterface/Systems/Chat/ChatUIController.Highlighting.cs
  Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
  Content.Client/UserInterface/Systems/Chat/Controls/ChannelFilterPopup.xaml.cs
  Content.Client/UserInterface/Systems/Chat/Controls/ChannelSelectorButton.cs
  Content.Client/_Starlight/Chat/CollectiveMindSystem.cs
  Content.Client/_Starlight/UserInterface/Controls/CharacterMindsControl.xaml
  Content.Client/_Starlight/UserInterface/Controls/CharacterMindsControl.xaml.cs
  Content.Server/CharacterInfo/CharacterInfoSystem.cs
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Server/GameTicking/Rules/ParadoxCloneRuleSystem.cs
  Content.Server/_Starlight/Chat/Commands/CollectiveMindCommand.cs
  Content.Shared/Body/Prototypes/BodyPrototypeSerializer.cs
  Content.Shared/CharacterInfo/SharedCharacterInfoSystem.cs
  Content.Shared/Chat/ChatChannel.cs
  Content.Shared/Chat/ChatSelectChannel.cs
  Content.Shared/Chat/SharedChatSystem.cs
  Content.Shared/Input/ContentKeyFunctions.cs
  Content.Shared/_Starlight/CollectiveMind/CollectiveMindComponent.cs
  Content.Shared/_Starlight/CollectiveMind/CollectiveMindPrototype.cs
  Content.Shared/_Starlight/CollectiveMind/CollectiveMindUpdateSystem.cs
  Resources/Locale/en-US/_Starlight/collective-mind/collective-mind.ftl
  Resources/Prototypes/Entities/Mobs/Species/diona.yml
  Resources/Prototypes/Entities/Mobs/base.yml
  Resources/Prototypes/_Starlight/CollectiveMinds/collective_mind.yml
  Resources/Prototypes/_Starlight/tags.yml
Labels: S: Needs Review, S: Untriaged, size/M, Changes: UI

#389 Revert stamina resistance
  Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Objects/Weapons/security.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#401 Added new law board recolors
  Resources/Prototypes/Entities/Objects/Devices/Circuitboards/law_boards.yml
  Resources/Textures/_Moffstation/Objects/Misc/module.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Misc/module.rsi/std_mod_black.png
  Resources/Textures/_Moffstation/Objects/Misc/module.rsi/std_mod_blue.png
  Resources/Textures/_Moffstation/Objects/Misc/module.rsi/std_mod_brown.png
  Resources/Textures/_Moffstation/Objects/Misc/module.rsi/std_mod_red.png
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#403 Fixed cargo arb test
  Content.IntegrationTests/Tests/CargoTest.cs
Labels: S: Needs Review, size/XS, S: Untriaged

#402 Revert adv. chem tweaks
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Recipes/Reactions/medicine.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged

#407 Fix Eclipse's Shotgun
  Resources/Prototypes/_Moffstation/PersonalItems/Items/Kento/Eclipse_Sunshade/eclipsetoyshotgun.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#411 Warden coat hood fix
  Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#390 Misc Loadout Improvements
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Loadouts/role_loadouts.yml
  Resources/Prototypes/_Moffstation/Loadouts/Miscellaneous/trinkets.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#408 High Value Target
  Content.Server/Objectives/Systems/PickObjectiveTargetSystem.cs
  Content.Server/_Moffstation/Objectives/Components/HighValueTargetSelectionComponent.cs
  Content.Server/_Moffstation/Objectives/Systems/HighValueTargetSelectionSystem.cs
  Resources/Locale/en-US/_Moffstation/roles/antags.ftl
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Prototypes/_Moffstation/Objectives/open_objectives.yml
  Resources/Prototypes/_Moffstation/Roles/Antags/syndicate.yml
Labels: S: Needs Review, S: Untriaged, size/M

#415 More LPO Tweaks
  Resources/Locale/en-US/_Moffstation/roles/antags.ftl
  Resources/Maps/_Moffstation/Nonstations/LPO.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/handheld_crew_monitor.yml
  Resources/Prototypes/_Moffstation/Loadouts/Antags/nukeops.yml
  Resources/Prototypes/_Moffstation/Loadouts/antag_loadout_groups.yml
  Resources/Prototypes/_Moffstation/Loadouts/antag_loadouts.yml
  Resources/Prototypes/_Moffstation/Roles/MindRoles/mind_roles.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Map

#409 Bumped up Nukie and Zombie Player Count
  Resources/Prototypes/GameRules/roundstart.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#413 New personal item: Remia/Loraine's pin
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/freianofvoid/Remia/remiaphoto.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Nox38/Aurora_Epiolos/auroraPin.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/freianofvoid/Remia Silkyflower/remiaPin.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/freianofvoid/Remia/remiaphoto.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/freianofvoid/Remia/remiaphoto.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Remia_Silkyflower/remiaPin.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Remia_Silkyflower/remiaPin.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Remia_Silkyflower/remiaPin.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Remia_Silkyflower/remiaPinInversed.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Remia_Silkyflower/remiaPinInversed.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/freianofvoid/Remia_Silkyflower/remiaPinInversed.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#427 Frezon fixes 1
  Resources/Maps/_Moffstation/frezon.yml
Labels: Changes: No C#, Changes: Map

#399 Visor Visual Fix
  Resources/Prototypes/Entities/Clothing/Head/helmets.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Head/helmets.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#420 Loadout Improvements Pt2
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Loadouts/role_loadouts.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/_Moffstation/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/_Moffstation/Loadouts/Jobs/security_officer.yml
  Resources/Prototypes/_Moffstation/Loadouts/Miscellaneous/trinkets.yml
Labels: Changes: No C#, S: Untriaged, size/M

#435 Personal Item: Rose's high-end headphones
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/roseheadphones.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/icon-on.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/off-equipped-EARS.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/off-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/off-equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/on-equipped-EARS.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/on-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/goblinsable/The_Rose_Of_Silence/The_Rose_Of_Silence.rsi/on-equipped-NECK.png
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#436 adds encryption key functionality to headphones
  Resources/Prototypes/Entities/Clothing/Multiple/misc.yml
Labels: S: Needs Review, Changes: No C#, size/XS

#442 Resomi can be butchered for 3 pieces of chicken.
  Resources/Prototypes/_Starlight/Entities/Mobs/Species/resomi.yml
Labels: S: Needs Review, Changes: No C#, size/XS

#423 New Map: Prime
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/_Harmony/Shuttles/emergency_jeremiah.yml
  Resources/Maps/_Harmony/prime.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/_Harmony/Maps/prime.yml
Labels: S: Needs Review, S: Untriaged, Changes: Map, size/XL

#439 small QoL change - recyclable books, flashlights, and powercells
  Resources/Prototypes/Entities/Objects/Misc/books.yml
  Resources/Prototypes/Entities/Objects/Power/powercells.yml
  Resources/Prototypes/Entities/Objects/Tools/flashlights.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#437 Added all three security belts to the secdrobe.
  Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
Labels: S: Needs Review, Changes: No C#, size/XS

#433 intercoms can be signalled now
  Content.Server/Radio/EntitySystems/RadioDeviceSystem.cs
  Content.Shared/Radio/Components/IntercomComponent.cs
  Resources/Locale/en-US/_Moffstation/device-linking/sink-ports.ftl
  Resources/Prototypes/Entities/Structures/Wallmounts/WallmountMachines/intercom.yml
  Resources/Prototypes/_Moffstation/DeviceLinking/sink_ports.yml
Labels: S: Needs Review, S: Untriaged, size/M

#450 Expanded loadout plushie options
  Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/plushies.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/_Moffstation/Loadouts/Miscellaneous/trinkets.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M

#448 2Fort for Gun Game
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/_Moffstation/Nonstations/ctf_2fort.yml
  Resources/Prototypes/_Moffstation/Maps/Pools/gungame.yml
  Resources/Prototypes/_Moffstation/Maps/arenas.yml
Labels: Changes: No C#, S: Untriaged, Changes: Map, size/XL

#460 Winter Coats are now Airtank and Guitar Compatible!
  Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
  Resources/Prototypes/Entities/Clothing/base_clothing.yml
Labels: Changes: No C#, size/XS

#467 Gamerules adjustments
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/_Moffstation/GameRules/roundstart.yml
  Resources/Prototypes/_Moffstation/secret_weights.yml
  Resources/Prototypes/game_presets.yml
  Resources/Prototypes/secret_weights.yml
Labels: S: Needs Review, Changes: No C#, size/S

#476 Fix Lobby Autopause
  Content.Server/GameTicking/GameTicker.Lobby.cs
Labels: S: Needs Review, size/XS, S: Untriaged

#479 Fix Licensing
  LICENSE.TXT
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#459 Tarbold Vent Critters (and burger)
  Resources/Locale/en-US/_Moffstation/ghost/ghost-role-component.ftl
  Resources/Locale/en-US/_Moffstation/name-identifier/name-identifier.ftl
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/_Moffstation/Entities/Mobs/NPCs/tarbold.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Consumable/Food/burger.yml
  Resources/Prototypes/_Moffstation/GameRules/pests.yml
  Resources/Prototypes/_Moffstation/Recipes/Cooking/meal_recipes.yml
  Resources/Prototypes/_Moffstation/name_identifier_groups.yml
  Resources/Textures/_Moffstation/Mobs/Animals/tarbold.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Animals/tarbold.rsi/outline.png
  Resources/Textures/_Moffstation/Mobs/Animals/tarbold.rsi/tarbold.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/tarburger.png
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#469 Adds Carolyn Flett's personal item
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Items/BulletKin/Carolyn__Flett/bulletcigspack.yml
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Carolyn_Flett/carolynflettcigspack.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Carolyn_Flett/carolynflettcigspack.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Carolyn_Flett/carolynflettcigspack.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Items/BulletKin/Carolyn_Flett/carolynflettcigspack.rsi/meta.json
Labels: Changes: No C#, S: Untriaged, Changes: Sprites

#458 Adds DeltaV's tape recorder
  Content.Client/_DV/TapeRecorder/TapeRecorderSystem.cs
  Content.Client/_DV/TapeRecorder/UI/TapeRecorderBoundUserInterface.cs
  Content.Client/_DV/TapeRecorder/UI/TapeRecorderWindow.xaml
  Content.Client/_DV/TapeRecorder/UI/TapeRecorderWindow.xaml.cs
  Content.Server/_DV/TapeRecorder/TapeRecorderSystem.cs
  Content.Shared/_DV/TapeRecorder/Components/ActiveTapeRecorderComponent.cs
  Content.Shared/_DV/TapeRecorder/Components/FitsInTapeRecorderComponent.cs
  Content.Shared/_DV/TapeRecorder/Components/TapeCasetteComponent.cs
  Content.Shared/_DV/TapeRecorder/Components/TapeRecorderComponent.cs
  Content.Shared/_DV/TapeRecorder/Systems/SharedTapeRecorderSystem.cs
  Content.Shared/_DV/TapeRecorder/TapeCasetteRecordedMessage.cs
  Content.Shared/_DV/TapeRecorder/TapeRecorderUI.cs
  Resources/Audio/_DeltaV/Items/TapeRecorder/attributions.yml
  Resources/Audio/_DeltaV/Items/TapeRecorder/play.ogg
  Resources/Audio/_DeltaV/Items/TapeRecorder/rewind.ogg
  Resources/Audio/_DeltaV/Items/TapeRecorder/stop.ogg
  Resources/Locale/en-US/_DeltaV/taperecorder/taperecorder.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/lawdrobe.yml
  Resources/Prototypes/Recipes/Lathes/Packs/service.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/reporter.yml
  Resources/Prototypes/_DeltaV/Catalog/Fills/Boxes/security.yml
  Resources/Prototypes/_DeltaV/Entities/Objects/Devices/tape_recorder.yml
  Resources/Prototypes/_DeltaV/Entities/Objects/Misc/paper.yml
  Resources/Prototypes/_DeltaV/Loadouts/Miscellaneous/trinkets.yml
  Resources/Prototypes/_DeltaV/Recipes/Lathes/misc.yml
  Resources/Textures/_DeltaV/Objects/Devices/cassette_tapes.rsi/meta.json
  Resources/Textures/_DeltaV/Objects/Devices/cassette_tapes.rsi/tape_greyscale.png
  Resources/Textures/_DeltaV/Objects/Devices/cassette_tapes.rsi/tape_ribbonoverlay.png
  Resources/Textures/_DeltaV/Objects/Devices/tape_recorder.rsi/empty.png
  Resources/Textures/_DeltaV/Objects/Devices/tape_recorder.rsi/idle.png
  Resources/Textures/_DeltaV/Objects/Devices/tape_recorder.rsi/inhand-left.png
  Resources/Textures/_DeltaV/Objects/Devices/tape_recorder.rsi/inhand-right.png
  Resources/Textures/_DeltaV/Objects/Devices/tape_recorder.rsi/meta.json
  Resources/Textures/_DeltaV/Objects/Devices/tape_recorder.rsi/playing.png
  Resources/Textures/_DeltaV/Objects/Devices/tape_recorder.rsi/recording.png
  Resources/Textures/_DeltaV/Objects/Devices/tape_recorder.rsi/rewinding.png
  Resources/Textures/_DeltaV/Objects/Storage/boxes.rsi/meta.json
  Resources/Textures/_DeltaV/Objects/Storage/boxes.rsi/recorder.png
Labels: S: Needs Review, Changes: Sprites, Changes: UI, size/L, Changes: Audio

#478 Malds the [Mald PR] Plushie sound 1984
  Resources/Prototypes/Entities/Objects/Fun/plushies.yml
Labels: S: Needs Review, Changes: No C#, size/XS

#483 Gungame Improvements
  Content.Server/_Moffstation/GameTicking/Rules/AvoidantSpawningSystem.cs
  Content.Server/_Moffstation/GameTicking/Rules/Components/AvoidantSpawningComponent.cs
  Content.Server/_Moffstation/GameTicking/Rules/Components/GunGameRuleComponent.cs
  Content.Server/_Moffstation/GameTicking/Rules/GunGameRuleSystem.cs
  Resources/Locale/en-US/_Moffstation/gungame/gungame.ftl
  Resources/Prototypes/_Moffstation/GameRules/gungame.yml
  Resources/Prototypes/_Moffstation/Loadouts/gungame_loadouts.yml
  Resources/Prototypes/_Moffstation/Roles/Jobs/Fun/gungame.yml
Labels: S: Needs Review, S: Untriaged, size/M

#475 Xeno Buff: Fixes
  Resources/Locale/en-US/_Moffstation/collective-mind/collective-mind.ftl
  Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/_Moffstation/CollectiveMinds/collective_mind.yml
  Resources/Prototypes/_Moffstation/tags.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M

#473 Marvin Dugmore's personal item (placebo effect)
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/icon-on.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/meta.json
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/off-equipped-EARS.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/off-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/off-equipped-NECK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/on-equipped-EARS.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/on-equipped-HELMET.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Pixel8/Marvin_Dugmore/marvinheadphones.rsi/on-equipped-NECK.png
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#484 Give reptilian's space dragon eye markings
  Resources/Locale/en-US/_Moffstation/markings/reptilian_markings.ftl
  Resources/Prototypes/_Moffstation/Entities/Mobs/Customization/Markings/reptilian_markings.yml
  Resources/Textures/_Moffstation/Mobs/Customization/Reptilian/dragon_eye.rsi/meta.json
  Resources/Textures/_Moffstation/Mobs/Customization/Reptilian/dragon_eye.rsi/tattoo_eye_dragon_color.png
  Resources/Textures/_Moffstation/Mobs/Customization/Reptilian/dragon_eye.rsi/tattoo_eye_dragon_shadow.png
Labels: Changes: No C#, size/S, S: Untriaged, Changes: Sprites
