Repository moff-station/moff-station-14, pull requests merged in 2025-09, with the labels that each got.

#511 Re-add Pre-1984 Use Delay on Plushies
  Resources/Prototypes/Entities/Objects/Fun/plushies.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#486 Gun Game: Respawn players even if a player wasn't what killed them
  Content.Server/_Moffstation/GameTicking/Rules/GunGameRuleSystem.cs
Labels: S: Needs Review, size/S, S: Untriaged

#517 Fix typo in Secret Gamemode weights
  Resources/Prototypes/_Moffstation/secret_weights.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#500 Marking limits
  Resources/Prototypes/Species/arachnid.yml
  Resources/Prototypes/Species/diona.yml
  Resources/Prototypes/Species/human.yml
  Resources/Prototypes/Species/moth.yml
  Resources/Prototypes/Species/reptilian.yml
  Resources/Prototypes/Species/slime.yml
  Resources/Prototypes/_CD/Species/avali.yml
Labels: Changes: No C#, size/S

#526 Reeducated borgs on how to hold delicate electronics
  Resources/Prototypes/_Moffstation/Entities/Objects/Misc/machine_parts.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#485 Gun Game Map Fixes
  Resources/Maps/_Moffstation/Nonstations/ctf_2fort.yml
  Resources/Maps/_Moffstation/Nonstations/d1_logic.yml
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Map

#533 Ready manifest adjustment
  Content.Server/_Moffstation/ReadyManifest/ReadyManifestSystem.cs
  Resources/Locale/en-US/_Moffstation/lobby/lobby-gui.ftl
Labels: S: Needs Review, size/XS, S: Untriaged, Changes: Sprites

#538 Increased arachnid crawl speed
  Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
Labels: S: Needs Review, Changes: No C#

#547 Adding Space Elephant Gun to syndicate uplink, Poachers to GunGame
  Resources/Locale/en-US/_Moffstation/store/uplink-catalog.ftl
  Resources/Prototypes/_Moffstation/Catalog/uplink_catalog.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
  Resources/Prototypes/_Moffstation/GameRules/gungame.yml
  Resources/Prototypes/_Moffstation/Loadouts/gungame_loadouts.yml
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Snipers/elephant_gun.rsi/base.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Snipers/elephant_gun.rsi/bolt-open.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Snipers/elephant_gun.rsi/equipped-BACKPACK.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Snipers/elephant_gun.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Snipers/elephant_gun.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Snipers/elephant_gun.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Snipers/elephant_gun.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Snipers/elephant_gun.rsi/wielded-inhand-left.png
  Resources/Textures/_Moffstation/Objects/Weapons/Guns/Snipers/elephant_gun.rsi/wielded-inhand-right.png
Labels: S: Needs Review, Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#541 Added Kuba's new personal item!
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Kubakura/Vex Glowsearcher/vexmask.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Kubakura/Vex_Glowsearcher/vexmask.rsi/equipped-MASK-vox.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Kubakura/Vex_Glowsearcher/vexmask.rsi/equipped-MASK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Kubakura/Vex_Glowsearcher/vexmask.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Kubakura/Vex_Glowsearcher/vexmask.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Kubakura/Vex_Glowsearcher/vexmask.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Kubakura/Vex_Glowsearcher/vexmask.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#548 Moffstation is now playable. (You can make burgers out of the cute mothroaches)
  Resources/Prototypes/_Moffstation/Entities/Objects/Consumable/Food/burger.yml
  Resources/Prototypes/_Moffstation/Recipes/Cooking/meal_recipes.yml
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/meta.json
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/mothroach-deathshead-inhand-left.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/mothroach-deathshead-inhand-right.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/mothroach-deathshead.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/mothroach-rosy-inhand-left.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/mothroach-rosy-inhand-right.png
  Resources/Textures/_Moffstation/Objects/Consumable/Food/burger.rsi/mothroach-rosy.png
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged, Changes: Sprites

#544 Prisoner outfits
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpskirts.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/_Moffstation/Loadouts/Non-Antags/prisoner.yml
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisoner.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisoner.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisoner.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisoner.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisoner.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpskirt/prisoner.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisoner.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisoner.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisoner.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisoner.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisoner.rsi/inhand-right.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/prisoner.rsi/meta.json
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/inhand-left.png
  Resources/Textures/_Moffstation/Clothing/Uniforms/Jumpsuit/shirtedprisoner.rsi/inhand-right.png
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#528 Job Title Loadouts
  Content.Server/StationRecords/Systems/StationRecordsSystem.cs
  Content.Server/_CD/Loadouts/RenameIdComponent.cs
  Content.Server/_CD/Loadouts/RenameIdSystem.cs
  Resources/Locale/en-US/_Moffstation/job/job-names.ftl
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Maps/amber.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/core.yml
  Resources/Prototypes/Maps/elkridge.yml
  Resources/Prototypes/Maps/exo.yml
  Resources/Prototypes/Maps/fland.yml
  Resources/Prototypes/Maps/loop.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Maps/oasis.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/packed.yml
  Resources/Prototypes/Maps/plasma.yml
  Resources/Prototypes/Maps/reach.yml
  Resources/Prototypes/Maps/relic.yml
  Resources/Prototypes/Maps/saltern.yml
  Resources/Prototypes/Maps/train.yml
  Resources/Prototypes/Maps/tram2.yml
  Resources/Prototypes/Maps/waterjug.yml
  Resources/Prototypes/_CD/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/_CD/Loadouts/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/_CD/Loadouts/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/_CD/Loadouts/Jobs/Science/scientist.yml
  Resources/Prototypes/_CD/Loadouts/Jobs/Security/security_officer.yml
  Resources/Prototypes/_Harmony/Maps/prime.yml
Labels: S: Needs Review, S: Untriaged, size/M, Changes: Map

#553 Fix Resomi Hardsuit Helmet Sprites
  Resources/Textures/Clothing/Head/Hardsuits/capspace.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Hardsuits/rd.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Hardsuits/security-red.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Hardsuits/security-warden.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Hardsuits/security.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Hardsuits/syndicate.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Hardsuits/syndiecommander.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Hardsuits/syndieelite.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Hardsuits/syndiemedic.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Helmets/atmos_firehelmet.rsi/on-equipped-HELMET-resomi.png
  Resources/Textures/Clothing/Head/Helmets/firehelmet.rsi/on-equipped-HELMET-resomi.png
Labels: Changes: No C#, size/XS, S: Untriaged, Changes: Sprites

#523 Makes more things signal triggerable
  Content.Server/Atmos/Portable/SpaceHeaterSystem.cs
  Content.Server/DeviceLinking/Systems/DeviceLinkSystem.cs
  Content.Server/Fax/FaxSystem.cs
  Content.Server/Lathe/LatheSystem.cs
  Content.Shared/Lathe/LatheComponent.cs
  Resources/Locale/en-US/_Moffstation/device-linking/sink-ports.ftl
  Resources/Prototypes/Entities/Objects/Weapons/security.yml
  Resources/Prototypes/Entities/Structures/Machines/fax_machine.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/portable.yml
  Resources/Prototypes/Entities/Structures/Specific/church-bell.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/Misc/bell.yml
  Resources/Prototypes/_Moffstation/DeviceLinking/sink_ports.yml
Labels: S: Needs Review, S: Untriaged, size/M

#558 Adds Talvi's XXXXL Hoodie
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/Altimus/Talvi_Frostmane/talvihoodie.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Altimus/Talvi_Frostmane/talvihoodie.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Altimus/Talvi_Frostmane/talvihoodie.rsi/folded-equipped-INNERCLOTHING.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Altimus/Talvi_Frostmane/talvihoodie.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Altimus/Talvi_Frostmane/talvihoodie.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Altimus/Talvi_Frostmane/talvihoodie.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/Altimus/Talvi_Frostmane/talvihoodie.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, Changes: Sprites

#546 Service cyborg module overhaul
  Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs
  Resources/Locale/en-US/_Moffstation/robotics/borg_modules.ftl
  Resources/Prototypes/Entities/Clothing/Multiple/towel.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/bowl.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/condiments.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/plate.yml
  Resources/Prototypes/Entities/Objects/Misc/utensils.yml
  Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
  Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
  Resources/Prototypes/Recipes/Lathes/Packs/robotics.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/_Moffstation/Recipes/Lathes/robot_modules.yml
  Resources/Prototypes/_Moffstation/tags.yml
  Resources/Prototypes/borg_types.yml
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/bureau-module.png
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/meta.json
  Resources/Textures/_Moffstation/Interface/Actions/actions_borg.rsi/service-module.png
  Resources/Textures/_Moffstation/Objects/Specific/Robotics/borgmodule.rsi/icon-bartending.png
  Resources/Textures/_Moffstation/Objects/Specific/Robotics/borgmodule.rsi/icon-bureaucracy.png
  Resources/Textures/_Moffstation/Objects/Specific/Robotics/borgmodule.rsi/meta.json
Labels: Changes: No C#, S: Untriaged, size/M, Changes: Sprites

#565 Increased sec rolling weight
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Labels: S: Needs Review, Changes: No C#, size/XS

#568 Network Configurator Recycle
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
Labels: S: Needs Review, Changes: No C#, size/XS, S: Untriaged

#571 Revert "Increased sec rolling weight"
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Labels: S: Needs Review, Changes: No C#, size/XS

#557 Captain's formal cape
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/Entities/Clothing/Neck/cloaks.yml
  Resources/Prototypes/_Moffstation/Loadouts/Jobs/captain.yml
  Resources/Textures/_Moffstation/Clothing/Neck/captain-cape.rsi/equipped-NECK.png
  Resources/Textures/_Moffstation/Clothing/Neck/captain-cape.rsi/icon.png
  Resources/Textures/_Moffstation/Clothing/Neck/captain-cape.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, size/S, Changes: Sprites

#560 ARGHH MORE PIRATE LOOT ADDED TO CARGO PIRATE CRATE ARGHHH
  Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
  Resources/Prototypes/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/_Moffstation/Entities/Objects/Weapons/Melee/pirate_hook.yml
Labels: S: Needs Review, Changes: No C#, size/S, S: Untriaged

#406 Watchlist admin overlay
  Content.Client/Administration/AdminNameOverlay.cs
  Content.Client/Administration/UI/Bwoink/BwoinkControl.xaml.cs
  Content.Server/Administration/Systems/AdminSystem.cs
  Content.Server/_Moffstation/Players/WatchListTracker.cs
  Content.Shared/Administration/PlayerInfo.cs
  Content.Shared/_Moffstation/CCVar/CCVars.Moff.cs
  Resources/Locale/en-US/_Moffstation/watchlist/watchlist.ftl
Labels: S: Needs Review, S: Untriaged, size/M, Changes: Sprites, Changes: Map, Changes: UI, Changes: Audio

#575 Fixed PDA duplication from titles
  Content.Server/_CD/Loadouts/RenameIdSystem.cs
Labels: S: Needs Review, size/XS, S: Untriaged

#569 Alt title icons
  Content.Server/_CD/Loadouts/RenameIdComponent.cs
  Content.Server/_CD/Loadouts/RenameIdSystem.cs
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/_CD/Entities/Objects/Devices/pda.yml
Labels: S: Needs Review, size/S, S: Untriaged

#577 Add Delilah's Courier Bag
  Resources/Prototypes/_Moffstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Moffstation/PersonalItems/Wearables/ScorchingRae/Delilah_Courrier/delilahbag.yml
  Resources/Textures/_Moffstation/PersonalItems/Wearables/ScorchingRae/Delilah_Courrier/delilahbag.rsi/equipped-BACKPACK.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/ScorchingRae/Delilah_Courrier/delilahbag.rsi/equipped-BELT.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/ScorchingRae/Delilah_Courrier/delilahbag.rsi/icon.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/ScorchingRae/Delilah_Courrier/delilahbag.rsi/inhand-left.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/ScorchingRae/Delilah_Courrier/delilahbag.rsi/inhand-right.png
  Resources/Textures/_Moffstation/PersonalItems/Wearables/ScorchingRae/Delilah_Courrier/delilahbag.rsi/meta.json
Labels: S: Needs Review, Changes: No C#, S: Untriaged, Changes: Sprites

#584 Update powergaming rules
  Resources/ServerInfo/_Moffstation/Guidebook/ServerRules/MoffR3Powergaming.xml
Labels: S: Needs Review, Changes: No C#, S: Untriaged

#598 upstream merge 9-28-25
  Content.Server/Atmos/EntitySystems/AirtightSystem.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.Airtight.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.GridMap.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.TileFill.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.cs
  Content.Shared/Damage/Components/DamageableComponent.cs
  Content.Shared/Damage/DamageSpecifier.cs
  Content.Shared/Damage/Systems/DamageableSystem.cs
  Content.Shared/Explosion/EntitySystems/SharedExplosionSystem.cs
  Content.Shared/Labels/EntitySystems/LabelSystem.cs
  Resources/Locale/en-US/tips.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Voice/speech_emote_sounds.yml
Labels: S: Needs Review, S: Untriaged, size/M

#599 Offbrand med fixes
  Content.Shared/_Offbrand/Wounds/MaximumDamageSystem.cs
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/Entities/Mobs/Species/slime.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
  Resources/Prototypes/Reagents/toxins.yml
  Resources/Prototypes/_Offbrand/base_mob.yml
  Resources/Prototypes/_Offbrand/surgery_graph.yml
  Resources/Prototypes/_Offbrand/zombification.yml
Labels: S: Needs Review, size/S, S: Untriaged

#601 Offmed Hotfix - Resomi
  Resources/Prototypes/_Starlight/Entities/Mobs/Species/resomi.yml
Labels: Changes: No C#, size/S

#581 Cleaned up cat ears
  Resources/Prototypes/Entities/Mobs/Customization/Markings/cat_parts.yml
  Resources/Prototypes/Species/human.yml
Labels: S: Needs Review, Changes: No C#, size/S

#592 Long speech (audio for full sentences)
  Content.Server/Speech/SpeechNoiseSystem.cs
  Content.Server/_Moffstation/Speech/LongSpeechComponent.cs
  Content.Server/_Moffstation/Speech/LongSpeechSystem.cs
  Resources/Audio/_Moffstation/Voice/Talk/arachnid.ogg
  Resources/Audio/_Moffstation/Voice/Talk/arachnid_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/arachnid_exclaim.ogg
  Resources/Audio/_Moffstation/Voice/Talk/attributions.yml
  Resources/Audio/_Moffstation/Voice/Talk/avali_1.ogg
  Resources/Audio/_Moffstation/Voice/Talk/avali_1_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/avali_1_exclaim.ogg
  Resources/Audio/_Moffstation/Voice/Talk/avali_2.ogg
  Resources/Audio/_Moffstation/Voice/Talk/avali_2_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/avali_2_exclaim.ogg
  Resources/Audio/_Moffstation/Voice/Talk/lizard.ogg
  Resources/Audio/_Moffstation/Voice/Talk/lizard_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/lizard_exclaim.ogg
  Resources/Audio/_Moffstation/Voice/Talk/resomi_1.ogg
  Resources/Audio/_Moffstation/Voice/Talk/resomi_1_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/resomi_1_exclaim.ogg
  Resources/Audio/_Moffstation/Voice/Talk/speak_4.ogg
  Resources/Audio/_Moffstation/Voice/Talk/speak_4_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/speak_4_exclaim.ogg
  Resources/Audio/_Moffstation/Voice/Talk/vox.ogg
  Resources/Audio/_Moffstation/Voice/Talk/vox_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/vox_exclaim.ogg
  Resources/Audio/_Moffstation/Voice/Talk/vulp.ogg
  Resources/Audio/_Moffstation/Voice/Talk/vulp_ask.ogg
  Resources/Audio/_Moffstation/Voice/Talk/vulp_exclaim.ogg
  Resources/Prototypes/Voice/speech_sounds.yml
  Resources/Prototypes/_CD/Voice/speech_sounds.yml
  Resources/Prototypes/_Moffstation/Voice/speech_sounds.yml
  Resources/Prototypes/_Starlight/Voice/speech_sounds.yml
Labels: S: Needs Review, S: Untriaged, size/M, Changes: Audio

#604 Craftable Brass Floor Can Actually Be Placed As a Floor Tile
  Resources/Prototypes/Tiles/floors.yml
Labels: Changes: No C#, size/XS, S: Untriaged
